### ISSUE TITLE
Navigation layout and formatting 

### ISSUE THREAD

**Issue by mingard** [dadi/publish#101]
- [x] Spaces between navigation buttons missing
- [x] Navigation not centred
<img width="84" alt="screen_shot_2017-03-19_at_12 19 34" src="https://cloud.githubusercontent.com/assets/1352469/24081430/18887378-0cab-11e7-9f43-962dfcd33fbb.png">
<img width="1353" alt="slack-imgs-2" src="https://cloud.githubusercontent.com/assets/1352469/24081426/09fc234a-0cab-11e7-9927-96e33dfe87dc.png">

**Comment by eduardoboucas** [comment]
> Spaces between navigation buttons missing

This was built as per the design. If we add margin between the buttons, we'll struggle to fit as many page numbers on the screen and I think they'll look too spaced between them.

> Navigation not centred

I believe this is no longer the case since I added the bulk actions controller in #104. Can you confirm?

**Comment by mingard** [comment]
Navigation seems better, we do need spacing between so please add after discussing with @abovebored

**Comment by eduardoboucas** [comment]
@abovebored over to you.

**Comment by abovebored** [comment]
Yep as @eduardoboucas says, keep it compact! Can review later if needed.

**Comment by mingard** [comment]
@abovebored The blocks are a bit tight, can we add spacing?

**Comment by mingard** [comment]
Temporarily added 1px.

<img width="190" alt="slack-imgs-4" src="https://cloud.githubusercontent.com/assets/1352469/24243281/7d3ccf4e-0fb2-11e7-9ff2-5d5ba40e9ce7.png">

Further feedback when you can @abovebored
