### ISSUE TITLE
Empty collection page

### ISSUE THREAD

**Issue by mingard** [dadi/publish#105]
When there are 0 documents in a collection, use layout specified in Redux

**Comment by eduardoboucas** [comment]
Not sure I understand this one. Are we talking about the document list view? And what layout are you talking about?

This is what currently happens:

<img width="1114" alt="screen shot on 2017-03-20 at 13_45_55" src="https://cloud.githubusercontent.com/assets/4162329/24102368/9df0ef22-0d73-11e7-8cb0-628c0ca0bb14.png">

We display the collection fields, just not any documents in the table. Can you elaborate on what you're proposing instead?

**Comment by mingard** [comment]
In the Redux document you'll see the intended layout of a collection with no documents

**Comment by eduardoboucas** [comment]
I still don't know what you're talking about, sorry. What is the Redux document?
