### ISSUE TITLE
Spec: Date component

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/publish#110]
There is the requirement to display dates with different formats throughout various parts of the application. I propose we build a `Date` component that will be used to display dates in a human-friendly format.

We've been using [Moment.js](https://momentjs.com/) for this in other products, but because we're talking about running it on the client-side, I propose we use [fecha](https://github.com/taylorhakes/fecha) instead, which is essentially a lightweight version of Moment (2.1KB versus 13.1KB).

This component would be able to:

1. Accept a date as a prop. This can be a `Date` object, ISO 8601 string or Unix timestamp;
1. Accept as a prop any date format supported by `fecha` (e.g. `'YYYY-MM-DD hh:mm:ss.SSS A'` or `shortTime`) to display the date
1. Alternatively to **2**, we can choose to display the date relatively to the current date and time. This would render things like "Just now", "5 minutes ago" and "Over a day ago", updated automatically with a sliding window interval.

**Comment by mingard** [comment]
Sounds great!

**Comment by eduardoboucas** [comment]
Done in #131.
