### ISSUE TITLE
Field permissions config

### ISSUE THREAD

**Issue by mingard** [dadi/publish#123]
Currently within the `display` block of a field we have `edit` and `index`, used to decide whether a field is displayed in either place.

There are some fields, such as `handle`, or `url` that are defined by hooks and are not subject to manual change. We need to extend both options, and move them into the publish block.

### Current
```json
 "type": "String",
      "label": "Title",
      "required": true,
      "message": "must be between 3 and 300 characters long",
      "display": {
        "index": true,
        "edit": true
      }
    }
```

### Suggested change

```json
 "type": "String",
      "label": "Title",
      "required": true,
      "message": "must be between 3 and 300 characters long",
      "publish": {
        "display": {
          "list": true,
          "editor": true
        },
        "readonly": true
      }
    }
```

**Comment by eduardoboucas** [comment]
Looks good to me, but I wonder if there's something at API level that could/should be done about this, since hooks are part of the core. It could make sense to add a `readonly` flag to the config schema, meaning that this field exists in the schema but you're not supposed to touch it.

**Comment by eduardoboucas** [comment]
And of course the above would be taken into consideration when doing validation at API level, which would probably save us some trouble on Publish side.

**Comment by mingard** [comment]
So you're thinking API would acknowledge the same settings? How would it differentiate between a change made by a hook and one made by API request? Would we need two variables here? `hook.readonly` and `request.readonly`?

How would we handle allowing `create` and `delete` but not `update`?

**Comment by mingard** [comment]
Scenario: 
- You want to allow users to create a handle, but not update it. 
- You want a hook to populate the handle if it wasn't populated by the API request.
- You want the hook to populate it if it was deleted by the API request.

**Comment by mingard** [comment]
I do like the simplicity of the `readonly` property though. Why don't we use that for now, inside the publish block. We can discuss permissions later as part of an API issue

**Comment by eduardoboucas** [comment]
Okay.

**Comment by mingard** [comment]
Updated description to match discussion. Look okay?

**Comment by eduardoboucas** [comment]
Fine with me.
