### ISSUE TITLE
App root logic

### ISSUE THREAD

**Issue by mingard** [dadi/publish#133]
At app root we currently have a sparse page. 

Current options are:
- Default redirect to first collection, in order of appearance with optional user preference collection
- A dashboard view
- Redirect to Profile view

Suggestions welcome

**Comment by eduardoboucas** [comment]
I think ultimately a dashboard would be nice, showing some stats about your own activity and some general data about articles being edited. But this sounds like post-MVP.

For MVP, I'd go with either:

- a redirect to first collection — could it be confusing to redirect people to a collection they might not even know exists, especially if they're new to the app?
- a message, in the style of [this page](http://publish.dl.dev.dadi.technology/empty.html), saying something like "Welcome, John Doe" and a very brief bit of copy explaining that the menu is organised by sections and collections etc.

**Comment by mingard** [comment]
Like the idea of having a basic welcome view for a user logged in for the first time. Selection of default collection etc as that can't always be achieved on signup (we may add batch creation of users, or import).

At a later stage, these settings can be used to direct editors to their chosen default.

For MVP, as you suggest, a redirect to first collection sounds good.

**Comment by eduardoboucas** [comment]
A temporary home view was added as part of #144. Should we close this ticket and open a post-MVP one at a later stage?

**Comment by mingard** [comment]
Yep
