### ISSUE TITLE
Changes to toolbar layout

### ISSUE THREAD

**Issue by mingard** [dadi/publish#148]
- [ ] Move delete button right, left of save button, with horizontal rule
- [ ] Move Created information to centre, vertically align
- [ ] Move active users far left

<img width="341" alt="screen shot 2017-04-03 at 09 43 25" src="https://cloud.githubusercontent.com/assets/1352469/24601753/08f9a46a-1852-11e7-9a7e-b1dcac01e456.png">
<img width="142" alt="screen shot 2017-04-03 at 09 44 25" src="https://cloud.githubusercontent.com/assets/1352469/24601787/28d93516-1852-11e7-802d-74418b0ed3e2.png">

**Comment by eduardoboucas** [comment]
*With peers:*

![screen shot 2017-04-03 at 17 50 52](https://cloud.githubusercontent.com/assets/4162329/24620602/2fa50746-1896-11e7-85db-317d66387f59.png)

*Without peers:*

![screen shot 2017-04-03 at 17 51 14](https://cloud.githubusercontent.com/assets/4162329/24620609/3278bc9c-1896-11e7-99d4-7166499b9a9d.png)

^ is that okay?

**Comment by mingard** [comment]
Central/vertical align 'Created at' and 'Last updated'. When no 'Last updated', make sure to vertically align 'Created At'. Horizontal split between delete and Save button too. 

Otherwise great!

**Comment by eduardoboucas** [comment]
*With peers:*

![screen shot 2017-04-04 at 10 46 23](https://cloud.githubusercontent.com/assets/4162329/24651048/32a7ed1c-1924-11e7-87b0-a0a5181e8ef5.png)

*Without peers:*

![screen shot 2017-04-04 at 10 46 48](https://cloud.githubusercontent.com/assets/4162329/24651054/38b22470-1924-11e7-90eb-12a5bfec1679.png)

*Without peers, single line:*

![screen shot 2017-04-04 at 10 47 15](https://cloud.githubusercontent.com/assets/4162329/24651062/3dcb8b5e-1924-11e7-9670-0d87c69f5bbe.png)
