### ISSUE TITLE
Localstore fails to update

### ISSUE THREAD

**Issue by mingard** [dadi/publish#149]
Steps to reproduce:
-  Open a document with text field
- Make a change to the text field
- Without selecting any other fields, hit refresh

The onChange event only fires when the field loses focus

**Comment by eduardoboucas** [comment]
To address this, we either start registering changes on every keystroke (which I don't think is a good idea) or we have a timer that forces an update every 2 seconds or something.

**Comment by mingard** [comment]
Can't we use a `beforeunload` event?

**Comment by eduardoboucas** [comment]
I had some issues with it in the past, but I'll give it a go.
