### ISSUE TITLE
Keyboard shortcuts - action list

### ISSUE THREAD

**Issue by mingard** [dadi/publish#153]
We have keyboard shortcuts working, but need a list of keys/actions to satisfy Redux requirements

**Comment by mingard** [comment]
@paulrgn any update?

**Comment by abovebored** [comment]
Feel free to update this list ya'll.

# Global

| Shortcut  | Action |
| ------------- | ------------- |
| <kbd>esc</kbd>  | Cancel current action  |
| <kbd>tab</kbd>  | Focus elements  |

# Documents index

| Shortcut  | Action |
| ------------- | ------------- |
| <kbd>cmd</kbd>+<kbd>F</kbd> | Focus search box |
| <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>F</kbd> | Open filters |
| <kbd>cmd</kbd>+<kbd>A</kbd> | Select all documents on page |
| <kbd>cmd</kbd>+<kbd>→</kbd> | Next page |
| <kbd>cmd</kbd>+<kbd>←</kbd> | Previous page |

# Document edit

| Shortcut  | Action |
| ------------- | ------------- |
| <kbd></kbd> | ...  |

**Comment by mingard** [comment]
@abovebored Thanks for this!

Couple of things to note:

- We no longer have a search input
- Filters are not a toggled property anymore

Perhaps cmd+f could add a filter?

I'll add the rest now. Let me know your thoughts.
