### ISSUE TITLE
Standardise field component props

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/publish#161]
As previously discussed, I think it would be great to standardise the props that field components receive. This would allow us to get rid of the `switch` statement that repeats a bespoke call to each component multiple times and would get us a step closer to loading these fields dynamically.

My idea is for the logic to eventually be something like this:

1. `DocumentEdit` iterates through fields, looks at its type/sub-type;
1. If there is a component that matches the name, call that component with a pre-defined, standardised list of props;
1. If not, skip the field.

From what I gather, these are the props that field components need:

- `config`: A chunk of the app config specific to the given field;
- `error`: Whether the field contains a validation error;
- `forceValidation`: If true, validation will be executed immediately and not only when the content of the field has changed (this is required for the save document process);
- `onChange`: Callback to be executed when there is a change in the value of the field;
- `onError`: Callback to be executed when there is a new validation error in the field;
- `value`: The field value;
- `schema`: The field schema.

Issue: `<FieldAsset>` is currently receiving an extra prop called `showPreview`. Is there any way we can change the component so it gets this information from somewhere else?

Any thoughts welcome. Thanks!

**Comment by mingard** [comment]
`showPreview` could be determined by the `accept` parameter. I'll look into changing that. The alternative is the create parent components for `FieldAsset` such as `FieldImage`, `FieldAudio` etc, but that seems like dumb logic.

**Comment by eduardoboucas** [comment]
> The alternative is the create parent components for FieldAsset such as FieldImage, FieldAudio etc, but that seems like dumb logic.

I don't think it's that dumb, to be honest. Even though these assets may use the same data representation, they may have particularities about them that makes different components an interesting option. It also makes the mapping of field type to component a bit easier: if the sub-type is `Image`, use `FieldImage`. No need to map multiple sub-types to `FieldAsset`.

I think the benefits we get justify the tiny overhead we create by having parent components.

**Comment by eduardoboucas** [comment]
In a way, it's the same thing as `<ButtonWithOptions>` using `<Button>` — it's using a smaller component and extending it with more functionality.

**Comment by mingard** [comment]
Creating 3+ components so that 2/3 set a param to true and 1/3 set it to false seems excessive, especially as within the child component we can determine that value.

**Comment by eduardoboucas** [comment]
I very much doubt that the only difference between a component that represents audio and one that holds an image is just those parameters. Surely you want to render different DOM elements, be able to play an audio track or zoom in on an image. Separate components would pave the way for those customisations.

Are you going to have a single component checking for a type and rendering `<audio>`, `<img>` etc. based on that?

**Comment by mingard** [comment]
As per our call lets go with your suggestion of single-use Fields. You have me convinced!

**Comment by eduardoboucas** [comment]
All field components now receive the exact same props and their docs have been updated. Example: https://github.com/dadi/publish/blob/master/docs/components/FieldString.md#props
