### ISSUE TITLE
Notify user when there are hidden selected documents

### ISSUE THREAD

**Issue by mingard** [dadi/publish#168]
### Where
Document List View
### When
Selecting documents for batch actions, or for Reference
### Requirement
A way (perhaps similar to Gmail) of alerting the user that they have selected documents that are not currently in view.
### Scenario
- User enters list view, page 1
- User checks/selects a document on page 1
- User navigates to page 2
- User checks/selects a document on page 2
- User uses batch actions to delete all selected documents
- User should be aware that they have pre-existing selections from another page

**Comment by abovebored** [comment]
How about where we have "Showing N of N" we switch this to "Selected N of N" and we highlight it in yellow? (as well as persisting it between pages)

<img width="182" alt="screen shot 2017-04-11 at 13 04 13" src="https://cloud.githubusercontent.com/assets/649231/24908294/63d9fcf2-1eb7-11e7-8c46-d7e49a1b0ab6.png">

Also from Gmail, there's that handy "Select **everything**" when select a whole page of results via the table header select box that could be nice to add in?

**Comment by mingard** [comment]
Like the sound of showing the selected total. Could we give it the ability to clear selection somehow?

Not sure about the select everything option, at least not until we have permissions. We'd also need to make it clear that it's all documents in the collection, and not just in view.

**Comment by abovebored** [comment]
Clear selection - sounds like a job for the `esc` key? As for UI, how about change the select all checkbox in the table header to a cross?

**Comment by mingard** [comment]
I'm not sure the `esc` is obvious enough  if it's the only method. 

Re selectall checkbox in `th`, that still needs to work as a select/deselect for the current page. For the entire selection we'd need something clearly relating the the entire selected list.

**Comment by abovebored** [comment]
> still needs to work as a select/deselect for the current page

**State 1: unchecked**
No documents selected

On click: Select all
Keyboard: Tab to move down list, space to select document

**State 2: checked**
All documents in current view selected (e.g., 20)

On click: unchecks, deselects all documents
Keyboard: esc clears all selection

**State 2: cross**
One or more documents selected

On click: swaps to unchecked, deselects all documents
Keyboard: esc clears all selection

Gmail function you ref is similar, except they use a [-]

<img width="83" alt="screen shot 2017-04-11 at 15 17 06" src="https://cloud.githubusercontent.com/assets/649231/24913733/f55a2ce4-1ec9-11e7-8b7f-ce2441c77369.png">

**Comment by abovebored** [comment]
TIL: https://css-tricks.com/indeterminate-checkboxes/

We should probably use that line through one!

**Comment by mingard** [comment]
Still not clear on what is supposed to happen when 100 documents are selected and only 20 are in view, perhaps not all in view selected. 

E.g. Select all of page 1, then 2, then 2 from page 3. 

The select toggle cannot be used on anything other than the documents in the current view so we still need something separate. Maybe I'm missing something with your description

**Comment by mingard** [comment]
@abovebored I have added the indeterminate checkbox as suggested. All that's left is finding a place for the "You have {selectedCount} other documents selected" to alert the user of other selected documents on other pages of the current collection. Gmail doesn't actually do this, and perhaps its not required. It does seem like a useful feature to have, especially when trying to avoid deleting documents that are selected but not in view.

**Comment by danwdart** [comment]
I remember being told "You're trying to do a select-all? We just did select all in view. Did you want to select all global? [button: Sure why not]"

**Comment by danwdart** [comment]
Would that be better?

**Comment by danwdart** [comment]
What's this waiting for?

**Comment by eduardoboucas** [comment]
> What's this waiting for?

I think this is waiting for some UI guidance. Pinging @abovedave and adding the corresponding label.

**Comment by eduardoboucas** [comment]
✅
