### ISSUE TITLE
Document documents.selectedDocuments

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/publish#171]
`documents.selectedDocuments` has been added to the documents store, documentation needs to be updated.

On a side note, does the property need to be called `selectedDocuments` since we're already inside the documents store? Could it be just `selected` or `selection`? This would be consistent with how things are named across other stores (e.g. `document.local` vs. `document.localDocument`).

**Comment by mingard** [comment]
@eduardoboucas yes I had thought it needed changing. `selected` sounds good
