### ISSUE TITLE
Write tests for back-end app

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/publish#183]
### Controllers
- [x] api-bridge
- [x] app-config
- [x] session

### Helpers
- [x] array
- [ ] collection-routes
- [x] regex
- [x] string 

### Models
- [ ] collections 

### Router
- [ ] index
- [x] routes/api-bridge
- [x] routes/app-config
- [x] routes/session

### Server

- [x] index
- [x] socket
- [x] socket_auth/authentication
- [ ] socket_auth/room

### Other

- [x] lib/constants
- [x] lib/index
- [x] config-schema
- [ ] config
- [x] globals
- [x] index

**Comment by eduardoboucas** [comment]
@mingard Do you fancy handling these when you're back, whilst I focus on the front-end component tests?

**Comment by mingard** [comment]
@eduardoboucas with pleasure

**Comment by eduardoboucas** [comment]
We currently have mocha set up for the back-end tests, but it might be worth using Jest too. Having a single test runner would simplify the setup, coverage reports, etc.

**Comment by mingard** [comment]
Sure. I'll take a look at Jest tomorrow
