### ISSUE TITLE
Incorrect media view redirect

### ISSUE THREAD

**Issue by mingard** [dadi/publish#189]
- Clear all available images from API
- Open existing document to edit
- Click 'Select existing image' on image field
- Observe 'No documents yet.' message
- Click create new document
- Observe a redirect to `/new` for the base collection

**Comment by eduardoboucas** [comment]
Should it display the button with the correct link to the referenced collection, or should we not display a button at all because we're not supporting creation of referenced documents as part of the editing workflow for MVP?

**Comment by mingard** [comment]
Option 2. We're not allowing direct creation of media as it currently serves no purpose. It should just alert the user that there's nothing to choose from.

**Comment by eduardoboucas** [comment]
Thanks!
