### ISSUE TITLE
Mobile view incorrectly showing

### ISSUE THREAD

**Issue by mingard** [dadi/publish#191]
Refreshing the document edit view occasionally shows the mobile view. It is then not possible to switch back without refresh.

**Comment by eduardoboucas** [comment]
Have you seen this happening straight after making changes to any of the files in the bundle, or not necessarily?

**Comment by mingard** [comment]
I'm not sure - is that where you see it?

**Comment by eduardoboucas** [comment]
I've seen this a couple of times, but I can only seem to replicate it right after making changes to the bundle, which leads me to believe it's a result of loading the app whilst something is still being rebuilt.

**Comment by mingard** [comment]
@eduardoboucas I believe this is, as you say, only appearing during build. Closing this, but will revisit if its seen in stable production
