### ISSUE TITLE
Unable to save images

### ISSUE THREAD

**Issue by mingard** [dadi/publish#192]
As per discussion in Slack:
- Unable to save images. 
- Changed https://github.com/dadi/publish/blob/master/frontend/actions/documentActions.js#L160 from `referencedCollection` to `referencedCollectionSchema`, which fixed the failed saving
- Now seeing images urls incorrectly formatted with `0.0.0.0` as domain

**Comment by eduardoboucas** [comment]
This is an API issue, captured [here](https://github.com/dadi/api/issues/245). Should we close this one?

**Comment by mingard** [comment]
Closing as superseded by https://github.com/dadi/api/issues/245
