### ISSUE TITLE
Message for empty filter results

### ISSUE THREAD

**Issue by mingard** [dadi/publish#193]
Currently if a filter fails to return any results the following message is returned. 
<img width="523" alt="screen shot 2017-04-24 at 11 41 12" src="https://cloud.githubusercontent.com/assets/1352469/25333655/fe914c5c-28e2-11e7-8c3e-26f19c37a49c.png">

Perhaps we can display something useful here? Hints on searching @abovebored?

**Comment by abovebored** [comment]
Could we use the 'empty' view, maybe with the following lines?

>**No documents found.**
>We can't find anything matching those filters.
>[Clear filters](#button)

**Comment by mingard** [comment]
@abovebored sure - maybe revisit further PMVP?

**Comment by abovebored** [comment]
Totally, something indicating in the filters themselves when you try to add one that would yield no results would be cool.

**Comment by mingard** [comment]
Yes! And perhaps spelling handling, or word proximity. 

> No results for 'unicarns'
> ## Did you mean 'unicorns'?
> | Clear filters **X** |

**Comment by jimlambie** [comment]
We show this when no documents. The other parts of this ticket could be made into new tickets if/when they are required.

<img width="504" alt="screen shot 2018-06-28 at 23 11 48" src="https://user-images.githubusercontent.com/116263/42030968-ad0e3e14-7b28-11e8-9d63-cf5fbda8b5f4.png">

**Comment by jimlambie** [comment]
Closing until required.
