### ISSUE TITLE
Reset password view

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/publish#195]
This is the only view left to do. From what I can see, we need:

**Back-end:**

- A password reset endpoint
- Generate a reset password token
- Send an email with a link to the endpoint + token
- Verify the token and reset the password

**Front-end:**

- The styled view

Thoughts @mingard?

**Comment by eduardoboucas** [comment]
Okay. If you let me know how the Publish endpoint for requesting a password reset will look like, I can work on the front-end part.

**Comment by eduardoboucas** [comment]
Do you have any information on what the endpoint will look like? Could we define it as `POST /reset` receiving an `email` property with the email address, returning a 200 with `success` as `true` or `false` depending on whether or not the address is valid, and a 500 if the email couldn't be sent?

**Comment by mingard** [comment]
@eduardoboucas that sounds reasonable. We could use `dadi/queue` for email services, and have API handle this, not Publish.

**Comment by eduardoboucas** [comment]
Isn't it a bit overkill to have a requirement for Queue just so we can send password reset emails, which will likely have a very low volume? Also, are you still happy to work on the back-end logic for this, or do you need help?

**Comment by mingard** [comment]
It would allow us to retain pending tasks and handle resending if there is a failure so better for error handling and non-blocking.

**Comment by eduardoboucas** [comment]
I understand that, but from what I understand, Queue is a microservice on its own, so at it currently stands it means deploying another service/web server. Is it reasonable to ask people to do this with the justification of being able to send password reset emails?

**Comment by mingard** [comment]
As per discussion, the following are required to complete this issue:
https://github.com/dadiplus/publish-api/issues/8
https://github.com/dadi/api/issues/254
https://github.com/dadi/publish/issues/210
https://github.com/dadi/publish/issues/211
