### ISSUE TITLE
Incorrect login details cause wrong error message

### ISSUE THREAD

**Issue by mingard** [dadi/publish#199]
We seem to have removed the error messages from session and replaced with a single 401. This means that incorrect password throws an unreachable API error

**Comment by eduardoboucas** [comment]
We're still sending information about the type of error and displaying the appropriate error message. This was working fine for me yesterday, I'll find out what changed.

**Comment by eduardoboucas** [comment]
The reason for this is [a PR on api-wrapper](https://github.com/dadi/api-wrapper/pull/37) that needed to be merged (I had the changes on my local environment). It has now been merged and it's deploying.

I'll close this issue after confirming that fixed the issue.

**Comment by eduardoboucas** [comment]
Working fine for me after:

```
npm update @dadi/api-wrapper
```

Can you confirm?

**Comment by mingard** [comment]
confirmed / closed
