### ISSUE TITLE
Config concept

### ISSUE THREAD

**Issue by mingard** [dadi/publish#21]
As per discussion with @josephdenne, a proposal for a concept that breaks down the required configuration blocks into apis and collections in order to limit the amount of api data stored in publish.

The `apis`, `structure` and `auth` blocks relate to an api, database and collection that holds further information. 

`apis` would list all connected `api` credentials, including **host**, **port**, **database** etc.
`auth` is a single collection containing the **users** for publish (and other apps in future)
`structure` would contain menu structure, such as sort ordering.

For now, we'll stick with the single config for MVP, or at least until just before release. This needs some serious scrutiny which we'll only find when we've exposed other MVP-related issues.

### Sample

```json
{
  "app": {
    "name": "DADI Publish",
    "publisher": "Publisher Name",
    "baseUrl": "http://am.dev.dadi.technology"
  },
  "server": {
    "host": "0.0.0.0",
    "port": 3000,
    "authenticate": true
  },
  "apis": {
      "name": "Publish Test API",
      "host": "http://am.dev.dadi.technology",
      "port": 3003,
      "collection": "apis",
      "database": "control",
      "version": "1.0",
      "credentials": {
        "clientId": "testClient",
        "secret": "superSecret"
    }
  },
  "structure": {
      "name": "Publish Test API",
      "host": "http://am.dev.dadi.technology",
      "port": 3003,
      "collection": "structure",
      "database": "control",
      "version": "1.0",
      "credentials": {
        "clientId": "testClient",
        "secret": "superSecret"
      }
   },
  "auth": {
    "host": "http://am.dev.dadi.technology",
    "port": 3003,
    "collection": "users",
    "database": "control",
    "version": "1.0",
    "credentials": {
      "clientId": "testClient",
      "secret": "superSecret"
    }
  }
}
```

**Comment by eduardoboucas** [comment]
👴
