### ISSUE TITLE
API check and create requirements

### ISSUE THREAD

**Issue by mingard** [dadi/publish#211]
Based on requirements in https://github.com/dadi/publish/issues/210, Publish scripts and package script block should include a requirement generation CLI tool.

It will find or create:
- [x] Auth collection check
- [x] Auth collection create/update
- [ ] Auth hook check
- [ ] Slugify hook check
- [ ] Auth hook create
- [ ] Slugify hook create

**Comment by mingard** [comment]
To run this, call `npm run api-install`

@eduardoboucas assigning to you as the auth collection `setConfig` method fails because. See https://github.com/dadi/api/issues/283.

Also I'm still waiting for the ability to get hook content.

**Comment by eduardoboucas** [comment]
> @eduardoboucas assigning to you as the auth collection setConfig method fails because. See dadi/api#283.

From reading the linked ticket, I can see this is no longer an issue, correct?

> Also I'm still waiting for the ability to get hook content.

This has been in API for a while. A `GET` to `/api/hooks/:hookName/config` will give you the hook content. We now also support `POST`, `PUT` and `DELETE`, see https://github.com/dadi/api/pull/256.

**Comment by eduardoboucas** [comment]
^ This has been added to `api-wrapper` and `api-wrapper-core` 🎉
