### ISSUE TITLE
Support for multiple and single reference field data

### ISSUE THREAD

**Issue by mingard** [dadi/publish#214]
We have a flag for multiple, which is used in Publish and exists only in the `publish` block.

Apart from changing the way content is displayed in Publish, this flag decides whether the Reference field can have one or many entries. 

The requirements outstanding, and for discussion:

- Multiple defaults to true
- If set to false, store as a single ObjectId, no array
- If true, store as an array of ObjectIds
- If limit is set, always store as an array, even if limit is 1
- Limit 0 defaults to no limit

 @jimlambie we may want to consider moving this out of the `publish` block, if we believe this should be enforced in API too

**Comment by eduardoboucas** [comment]
I can get started on this. If we decide to make it part of API, I'll just need to look for `settings.limit` instead of `publish.limit`.

**Comment by mingard** [comment]
Yes please

**Comment by eduardoboucas** [comment]
I've made API format multiple media documents (in array format as well as single ObjectID). It doesn't seem to currently resolve non-media references in array format, so I'll address that first before I can finish the Publish piece. 👷

**Comment by jimlambie** [comment]
@mingard "multiple" should already be in the Reference field settings, not the publish block?

**Comment by mingard** [comment]
@eduardoboucas sounds good, thanks!
@jimlambie Okay, what affect does if have? Is there a limit value that limits the number of referenced documents in the array?

**Comment by eduardoboucas** [comment]
Done in #232.
