### ISSUE TITLE
Block unauthenticated session check

### ISSUE THREAD

**Issue by mingard** [dadi/publish#218]
When loading the signin page, a session check resulting in a 401 (as expected) as running. This should be captured to avoid console logging. Perhaps changing the 401 header to a 200 with a meaningful response body is the answer.

**Comment by eduardoboucas** [comment]
Why should we avoid console logging? We should be informing the browser that the authentication failed and 401 seems like the correct code to do that.

**Comment by mingard** [comment]
We don't really need to inform the browser, just the app. I see no reason to have an error throwing to console when you hit the sign in page

**Comment by mingard** [comment]
As per https://bugs.webkit.org/show_bug.cgi?id=37215 general consensus is that this is a useful error when requesting an unauthorised resource, however I'm leaving this open to discuss how we might handle the failed session check, as it should not be considered an inaccessible resource, but a resource with a body with a meaningful message relating to the state of the current session.
