### ISSUE TITLE
Random DADI background

### ISSUE THREAD

**Issue by mingard** [dadi/publish#219]
Rather than using a static image, Publish should use [Pattern Generator](https://github.com/dadi/pattern-generator)

**Comment by mingard** [comment]
We're restricted by the size of the [minified pattern generator](https://dadi.tech/assets/js/pattern.min.js), which is approx 25kb.

This requires a major refactor so currently this ticket is blocked.

**Comment by mingard** [comment]
For MVP this should cycle through 10x versions of the background. @abovebored are you able to supply these? Current version is 131kb but ideally the entire 10x would be less than 100kb.

**Comment by abovebored** [comment]
Can you try with these three SVG files (total 102kb).

http://cloud.dadi.technology/JHyYb/4FBSXlpK

I think there's enough going on that you will not notice a repeat. We could also try rotating by 180 degrees and flipping the background container to get 6 more variations.

Flip: `transform: scaleX(-1);`
Rotate: `transform: rotate(180deg);`

**Comment by mingard** [comment]
@abovebored Good shout. We'll add these now - thank you.
