### ISSUE TITLE
Image drop area to cover entire block

### ISSUE THREAD

**Issue by mingard** [dadi/publish#226]
- The listener for image drop zone should cover entire block.
- Options such as 'Select existing Image' should be hidden. 
- The block should be very simple, with the text 'Drop Image here' front and center.

**Comment by eduardoboucas** [comment]
To confirm, the block would still look the same on its normal state, but when dragging a file elements like "Select existing image" or "Select from device" would be hidden and only the drop zone is shown. Is this correct?

**Comment by mingard** [comment]
@eduardoboucas yes thats right
