### ISSUE TITLE
Validation parameter to fields

### ISSUE THREAD

**Issue by mingard** [dadi/publish#233]
For both API driven validation and local validation (checking email is valid on signin and password reset) we should separate validation as a parameter that we pass to Fields, rather than using the onChange event.

**Comment by eduardoboucas** [comment]
We currently load fields dynamically, always passing to them the exact same set of data, and then each field type handles its own validation. With what you're proposing, where would the validation logic live and how would you know what validation logic to pass to each field type?

**Comment by mingard** [comment]
Every Field type would have a validation method pushed to it. We'd interpret the validation block in config and pass that as a single method. I've applied this method to the password reset view. You can see it in action there.

**Comment by eduardoboucas** [comment]
> Every Field type would have a validation method pushed to it.

But where would those methods live?

**Comment by mingard** [comment]
Currently undecided.

**Comment by eduardoboucas** [comment]
I think we should avoid moving logic that should belong in each specific field into a global validation system. It harms modularity and raises questions around how custom fields would work.

**Comment by mingard** [comment]
> I think we should avoid moving logic
We aren't moving logic, we're creating it
> global validation system
The definitions of the validation will be called based on the field type, but be part of a centralised validation method. As validation should only be applied based on API accepted validation formats, I see no harm in this.

**Comment by mingard** [comment]
Take `FieldString` for example. If we want to introduce a validation method in the field, we need to define not only the parameters that the value will be validated against, but a method to handle this. We'll have to introduce that into all fields that have any form of validation.

What I'm building is a single Validation class that can be used in any field. Current format looks like:

```javascript
handleValidation(value) {
  const {schema} = this.props
  const isValid = new Validation(schema.validation)
}
````

The `Validation` class will analyse the `validation` block, looking at everything from `minLength` to `regex`.

**Comment by eduardoboucas** [comment]
We'll get this rolling once https://github.com/dadi/api/issues/451 is in.

**Comment by eduardoboucas** [comment]
> We'll get this rolling once dadi/api#451 is in.

✅
