### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by mingard** [dadi/publish#265]
Inline with the other dadi microservices, the npm module name should change from `publish` to `@dadi/publish`. 

The added complication here is that previous attempts to do this caused errors when running as a git npm module dependency in another app.

e.g.

```json
{
  "name": "my-app",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.js --node-env=development"
  },
  "dependencies": {
    "@dadi/publish": "github:dadi/publish"
  }
}
```

**Comment by jimlambie** [comment]
Any indication what errors it caused?
