### ISSUE TITLE
Field settings with "display" property don't appear

### ISSUE THREAD

**Issue by jimlambie** [dadi/publish#278]
A field with publish settings which include a "display" property don't appear in the interface:

```
"publish": {
  "display": {
    "list": true,
    "edit": true
  }
}
```

**Comment by eduardoboucas** [comment]
@mingard This might be one for you, as you worked on this piece?

**Comment by mingard** [comment]
What is the field type? Some don't have list view right @eduardoboucas ?

**Comment by eduardoboucas** [comment]
It's a `String`, apparently. The issue only happens when `display` is added to the `publish` block.
