### ISSUE TITLE
Display collection name on index view

### ISSUE THREAD

**Issue by jimlambie** [dadi/publish#279]
There's no indication which collection you're currently editing:

<img width="634" alt="screen shot 2017-06-28 at 12 40 33" src="https://user-images.githubusercontent.com/116263/27635655-c8e0aa80-5bff-11e7-8930-aecda496ce83.png">

**Comment by eduardoboucas** [comment]
I think this one needs some guidance from @abovebored.

**Comment by jimlambie** [comment]
@mingard @abovebored I think we should bring this one back - it can't be that hard to display the current collection name?
