### ISSUE TITLE
Docs 

### ISSUE THREAD

**Issue by ikaikahussey** [dadi/publish#284]
Hi --

Looking forward to trying Publish out but the docs are 404. Is there a better link? Thanks!

**Comment by mingard** [comment]
@ikaikahussey Sorry for the trouble you've had with the docs and the 404 message. I'll make sure that link is removed from the README. 

In terms of Docs, there is a docs directory in this repository which should help explain the component architecture as well as some of the key concepts. 

We're just building in some tests. The next phase will be to add docs, which should happen soon.

If you'd like, I can talk you through the basic setup. We have a [public Slack portal](http://chat.dadi.tech) where you can find me and other core engineers.
