### ISSUE TITLE
Review legacy auth against API 4

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/publish#286]
API 2.2.0 introduced a new format for custom errors in hooks, so the auth hook needs to be re-tested and possibly adjusted to reflect the changes.

**Comment by mingard** [comment]
@eduardoboucas have you been able to test this? What do we need to look out for?

**Comment by eduardoboucas** [comment]
The priority for this should be defined based on how/when we see implementation with API 4.0 (and ACL in particular) happening, as we will decommission the auth hook at that point.

**Comment by eduardoboucas** [comment]
✅ 🕸
