### ISSUE TITLE
Support for modular components

### ISSUE THREAD

**Issue by mingard** [dadi/publish#299]
## Overview
As it is often the case that projects require custom fields and other client specific functionality, we must find a way to support building these into the webpack bundle process.

## Spec
- Workspace directory to contain `fields`
- Build process to include workspace directory
- Watch running at all times for rebuild
- Move assets into workspace directory when running as module

@eduardoboucas @jimlambie can you see any potential roadblocks with this method? Are there other options available?

**Comment by jimlambie** [comment]
See also https://github.com/dadi/publish/issues/395
