### ISSUE TITLE
Reference document editing

### ISSUE THREAD

**Issue by mingard** [dadi/publish#300]
As API now fully supports Reference document creating/editing Publish must support this with the following:
- [x] Reference url structure
- [x] Create multiple new Referenced documents (url format: `/:referencedCollection/new/:pos`)
- [ ] Handle all image upload prior to save

@eduardoboucas can you see anything missing here?

**Comment by eduardoboucas** [comment]
The only outstanding item here is captured in https://github.com/dadi/publish/issues/248. Closing.
