### ISSUE TITLE
Handle Insecure API calls when Publish is running on SSL

### ISSUE THREAD

**Issue by mingard** [dadi/publish#301]
Ajax requests when Publish is running securely but API is not will fail. This happens when POSTing images over ajax from the frontend app.

Our options:
- Don't allow any API that is running insecurely when Publish is secure
- Allow insecure APIs, but limit ajax requests with a warning

Thoughts @jimlambie @eduardoboucas @josephdenne?

**Comment by jimlambie** [comment]
A warning to be covered in documentation, not in software. Closing/
