### ISSUE TITLE
Improve method for editing Referenced documents

### ISSUE THREAD

**Issue by mingard** [dadi/publish#303]
Currently we store the local and remote parent document in state. Changes to local are applied to local on change, and to remote on save.
Editing a document that is already referenced should be fine, because we already have it as part of the parent document e.g.

```js
const local = {
  _id: "593fee8cd8ab693784c139ac",
  title: "New article",
  referencedDocuments: [
    {
      _id: "5981c27f81cf2240dda42c93",
      title: "Article Sub Document"
    }
  ]
}
```

If a user has not selected any Referenced documents, but has transitions from Parent > referencedDocuments (List view) > referencedDocuments (Edit view for "5981c27f81cf2240dda42c93") and the Parent document still looks like this:

```js
const local = {
  _id: "593fee8cd8ab693784c139ac",
  title: "New article",
  referencedDocuments: []
}
```

…we have an issue. The `documentData`, which is always the Parent document, can’t be updated. 

When editing a sub document, do we want to:
a) Present the user with save button specifically for changes to the sub-document
b) Store the changes locally, and save with the parent document

Advantages of _a_ is that we don’t ever have to store a large diff on changes. disadvantage is that it might be tricky to explain to a user that they are only saving the sub document, not the parent.

Advantages of _b_ is that with a complete diff of all changes, a page refresh when editing a Reference document won’t lose unsaved changes to the Parent. Disadvantage is that changes to sub documents will only be applied if the sub document is also selected by the parent. If it is edited, but never selected in the Reference document list view, it won’t be part of the payload.

**Comment by mingard** [comment]
As per discussion with @eduardoboucas:

- All changes are to be stored in a single tree
- The creation of a sub document will always add in an empty object in either a new or existing array
- Cancelling changes will remove this object from the array
- Making changes to a sub document, itself referenced in a _new_ sub document will only be possible once the document has been selected.
- Removal of the sub document from the list should warn user that the changes they have made to the sub document will not be saved. (It could perhaps ask them if they'd like to save the changes even though the sub document is no longer referenced)

**Comment by jimlambie** [comment]
@eduardoboucas for your review regarding whether this is still a thing

**Comment by jimlambie** [comment]
Seems like not a thing...

**Comment by eduardoboucas** [comment]
Not immediately applicable given the current state of references. Let's reopen in the future if needed.
