### ISSUE TITLE
Navigation z-index above menu

### ISSUE THREAD

**Issue by mingard** [dadi/publish#305]
When the top level nav extends to a second row, the menu for the first row becomes unusable.
<img width="347" alt="screenshot 2017-08-15 12 24 56" src="https://user-images.githubusercontent.com/1352469/29314185-d6fe9034-81b4-11e7-94bd-015941f1024d.png">

**Comment by eduardoboucas** [comment]
It needs investigation to assess whether it's still an issue. If it's not, please close!

**Comment by jimlambie** [comment]
Ok, so it's resolved.

However, I'm not a fan of the text-shadow added to the parent nav item when the dropdown appears - it gives it a blurry effect?

**Comment by jimlambie** [comment]
http://publish-fix-dropdown-nav-z-index.eb.dev.dadi.technology/

**Comment by danwdart** [comment]
Ah, so it reflowed and redrew when I used actual font-weight, making the container box a different size. We can't use static sizes, so I wasn't sure what to do other than this.

**Comment by jimlambie** [comment]
@danwdart in that case, perhaps we leave it out. Let's keep the z-index change (👍 ) but remove the text-shadow change. Then we can release.

**Comment by danwdart** [comment]
Okay cool.

**Comment by danwdart** [comment]
I think the emboldening must be merged or on another branch because this PR only looks at the z-index now
