### ISSUE TITLE
Write tests for frontend js

### ISSUE THREAD

**Issue by mingard** [dadi/publish#311]
Coverage to include:

- [x] lib/util/array
- [x] lib/util/index
- [x] lib/util/string
- [x] lib/util/url-helper
- [x] lib/util/validation
- [ ] lib/analytics
- [ ] lib/api-bridge-client
- [ ] lib/collection-lookup
- [ ] lib/constants
- [ ] lib/datetime
- [ ] lib/document-routes
- [ ] lib/field-components
- [ ] lib/fields
- [ ] lib/keyboard
- [ ] lib/local-storage
- [ ] lib/redux
- [ ] lib/router
- [ ] lib/socket
- [ ] lib/status
- [ ] lib/Style

**Comment by eduardoboucas** [comment]
Closing, as we moved to a functional test suite.
