### ISSUE TITLE
FieldDateTimeFilter/FieldNumberFilter not working

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/publish#318]
Screencast: https://dadi.slack.com/files/U0DM542GJ/F78ELT34L/fielddatetimefilter_weirdness.mov

Also, the `<select>` needs to be updated to include the `value` prop, as opposed to using `selected` in the individual `<option>` nodes.

**Comment by eduardoboucas** [comment]
@mingard The problem is also visible in `FieldNumber`. Tests on that part of the component are blocked by this issue.

**Comment by eduardoboucas** [comment]
Not sure if this helps, but [here](https://github.com/dadi/publish/blob/04a4133c6963fb62734d07ea582dea2ca820f75d/frontend/components/FieldNumber/FieldNumberFilter.jsx#L102) we seem to be enforcing that `event.target.value` must be a number, which isn't the case when you're changing the filter type.

**Comment by mingard** [comment]
Re `FieldNumber`, this has been resolved.
