### ISSUE TITLE
Add edit button to Reference document list

### ISSUE THREAD

**Issue by mingard** [dadi/publish#325]
For a Reference field, each item should show an _edit_ button which will take the user through to that document to edit it.

**Comment by mingard** [comment]
If at all possible it would be great to prioritise this one. Having to remove all selected referenced documents before updating is slow, and can sometimes requires taking note of the current selection in order to recreate.
<img width="515" alt="screen shot 2018-07-28 at 08 05 17" src="https://user-images.githubusercontent.com/1352469/43354061-febaa59c-923c-11e8-8917-771d3f091915.png">

**Comment by danwdart** [comment]
I don't like this design of "pick one from somewhere and you have to remove it if you want to change it" - wouldn't a dropdown / multiselect dropdown be better here?

**Comment by danwdart** [comment]
@jimlambie what's blocked about this?

**Comment by mingard** [comment]
@danwdart for now it would be great if it just followed the same journey as making the initial selection. It just needs an ‘edit’ button that takes you through to the list. Drop down isn’t a choice here, it could be a selection from a collection with thousands of entries, or one with long text field content that can’t be displayed this way.

**Comment by danwdart** [comment]
yep

**Comment by danwdart** [comment]
I think for now we decided that the Edit button would be the same as the Choose button but with pre-filled documents, and that Remove was to be renamed to Remove All, right? Can we unblock or does this need extra?

**Comment by eduardoboucas** [comment]
Assigning to me, as I've (inadvertently) started working on this. 😑
