### ISSUE TITLE
Provide friendly error for incorrect login

### ISSUE THREAD

**Issue by jimlambie** [dadi/publish#326]
When logging in with incorrect email + password, the sign-in screen shows "Authentication API Unreachable" - which is not strictly the case

This error is output in the log (three times!)
```
{"name":"dadi-dadi-api","hostname":"ip-172-31-22-165","pid":19244,"level":50,"module":"api","msg":"[ { code: 'API-0002',\n    title: 'Hook Error',\n    details: 'The hook \\'publish-auth\\' failed: \\'WRONG_CREDENTIALS\\'',\n    docLink: 'http://docs.dadi.tech/errors/api/API-0002' } ]","time":"2017-10-10T10:34:36.064Z","v":0}
```

**Comment by abovebored** [comment]
🤖

**Comment by mingard** [comment]
@jimlambie This has been fixed, but requires some changes in your API. 

You'll need to replace the hook with this version https://github.com/dadi/publish/blob/master/scripts/api-install/hooks/publish-auth.js

The new version of Publish is not live on NPM yet, so you'll have to reference `github:dadi/publish`
