### ISSUE TITLE
Sign-in screen still visible after successful signin

### ISSUE THREAD

**Issue by jimlambie** [dadi/publish#333]
After entering a valid email address and password, the user is logged in but the sign-in screen is still shown.

Expectation is that the Welcome screen is shown.

**Comment by mingard** [comment]
Confirming unable to replicate this @jimlambie - will leave the ticket here for now.

**Comment by mingard** [comment]
Able to replicate this, but only when build process is still active. Closing, but please reopen if you're able to replicate again @jimlambie.
