### ISSUE TITLE
Passwords in plain text in logs

### ISSUE THREAD

**Issue by jimlambie** [dadi/publish#334]
Publish sends a GET request to API to retrieve a user matching the entered email address and password, but the password is plain text

```
{
  "name":"dadi-dadi-api",
  "hostname":"Jamess-MacBook.local",
  "pid":7763,
  "level":30,
  "module":"router",
  "msg":"GET /1.0/publish/users?filter=%7B%22email%22:%22jl@dadi.co%22,%22password%22:%22password%22%7D 200 254ms",
  "time":"2017-10-12T17:36:01.483Z",
  "v":0
}
```

**Comment by mingard** [comment]
@jimlambie What would be your preference here?

**Comment by jimlambie** [comment]
@mingard perhaps a query by email address only, then compare the supplied password with a stored hash within Publish once a user result has been obtained?

**Comment by mingard** [comment]
@jimlambie I'd like to avoid bringing any of the password hashing logic into Publish.

**Comment by jimlambie** [comment]
Why? It's a simple operation. Why do we need to rely on the connected API to handle it?

**Comment by mingard** [comment]
Because Publish isn't supposed to handle the creation of Password hashes, or any other data logic, regardless of simplicity. Auth is entirely handled by API, hence the need for a connection.

**Comment by mingard** [comment]
We could potentially change from `GET` to `POST`. This would be a breaking change, as the accompanying hook in API would need to change.

**Comment by eduardoboucas** [comment]
Moved to Logger. https://github.com/dadi/logger/issues/59
