### ISSUE TITLE
Validation error display

### ISSUE THREAD

**Issue by jimlambie** [dadi/publish#336]
When saving an empty document, all required fields show a validation error, which is 👍 

However, there are required fields in another tab - the tab is shown with a red dot but navigating to the tab reveals no fields with a red box+message. the first field _should_ have a red validation error, but does not.

From API log:

```
     { field: 'primaryCategory', message: 'must be specified' } 
```

From browser:

<img width="210" alt="screen shot 2017-10-12 at 18 51 10" src="https://user-images.githubusercontent.com/116263/31511542-f7cf47d8-af7f-11e7-82f5-e457a16b1b22.png">

**Comment by danwdart** [comment]
I can't reproduce this one - has it been fixed? E.g. http://localhost:3001/content/pages/new/meta popped up the red dot on Details and going there showed me some red outlined fields

**Comment by eduardoboucas** [comment]
@jimlambie Are you able to reproduce this on the preview instance, or provide a collection schema where it can be reproduced?

**Comment by jimlambie** [comment]
@eduardoboucas @danwdart I cannot reproduce, let's consider it closed. Thanks!
