### ISSUE TITLE
Can't add first field as filter

### ISSUE THREAD

**Issue by jimlambie** [dadi/publish#337]
When click Add Filter, a dropdown appears with the list of fields for filtering on, with the first field selected. The Apply Filter button is not available until making a different field selection.

Browser: Firefox

<img width="511" alt="screen shot 2017-10-12 at 19 04 35" src="https://user-images.githubusercontent.com/116263/31511678-64a7a04e-af80-11e7-8c0d-f3aaf019bf3b.png">

**Comment by jimlambie** [comment]
Looks like this is something to do with a date filter? I see other fields populate the predicate dropdown and have a value field...

**Comment by mingard** [comment]
@jimlambie Publish version?
The date filter seems to be working for me in firefox. There are some other issues with the table formatting though.
