### ISSUE TITLE
Overactive menu items

### ISSUE THREAD

**Issue by jimlambie** [dadi/publish#338]
See image... two menu items have been given the class "active" ... are the names too similar?

<img width="419" alt="screen shot 2017-10-12 at 19 08 55" src="https://user-images.githubusercontent.com/116263/31511856-ea6cac42-af80-11e7-9478-9e001838835e.png">

**Comment by mingard** [comment]
@jimlambie strange. I can't replicate this. 

What are the names of the collections?
Can you share the Publish menu settings block?
