### ISSUE TITLE
Make a more obvious "Select all"

### ISSUE THREAD

**Issue by jimlambie** [dadi/publish#342]
The "Select all" checkbox in the list view needs to be more obviously "Select all"... could we make it a button, or give it a hover state/tooltip/title?

<img width="301" alt="screen shot 2017-10-16 at 14 49 00" src="https://user-images.githubusercontent.com/116263/31615536-c351f65e-b281-11e7-947b-09d277b40aad.png">

**Comment by mingard** [comment]
@jimlambie Wrapping it in a button would work, as long as it still had an intermediate state. 

@abovebored one to discuss during review?

**Comment by danwdart** [comment]
I'd suggest looking for an example that does it well. Except Gmail, that's weird.

**Comment by danwdart** [comment]
Was this discussed any more and not included here?

**Comment by danwdart** [comment]
Was this decided upon? That looks natural to me though. It could just be a title attribute?

**Comment by eduardoboucas** [comment]
This wasn't discussed. It's probably best if you ask @abovedave or @joverbye about it.

**Comment by abovedave** [comment]
My view is I think it's obviously enough as is and the stakes are low enough that using it would teach the user without any risk of deleting data etc.

**Comment by danwdart** [comment]
So your suggestion is do nothing?

**Comment by eduardoboucas** [comment]
@jimlambie you raised this one – how do you feel about it these days?

**Comment by jimlambie** [comment]
@eduardoboucas I'm happy for it to be closed if no one else considers it essential for intuitive use of the interface
