### ISSUE TITLE
Support multiple referenced images

### ISSUE THREAD

**Issue by mingard** [dadi/publish#348]
It is currently possible to select multiple reference images, but not possible to then edit, select and deselect images.

**Comment by danwdart** [comment]
I recall the discussion about this - did we want to show a similar "edit" / "delete" UI as text arrays?

**Comment by jimlambie** [comment]
@danwdart exactly that, yes - so clicking "Edit" would take you to the media collection selection page

**Comment by anaumovets** [comment]
Some general questions about FileImageEdit:
1. We have file name "blabla.png" and then a number of files referenced under that name. What does that mean? More generally, what's the usage scenario for this component case of multiple files?
2. What to do when an existing file is uploaded (via select from device)? Currently, a duplicate is added - that doesn't feel right.

**Comment by danwdart** [comment]
I don't think that's right though - isn't it supposed to be for multiple different images?

**Comment by eduardoboucas** [comment]
🚢
