### ISSUE TITLE
Boolean field not passed as explicitly false

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#363]
### Expected behavior

When a Boolean field is saved, I expect the API to record `"value": false`. This means in a Web datasource you cannot filter on the value being false e.g., if the field was "Is Published? [true|false]

```
filter": {
   "isPublished": false
}
```

The work around is to use a mongo query:

```
"filter": {
    "isPublished": { "$ne": true} }
}
```

### Actual behavior

The value is omitted from the API document (assume not passed because it's false).

### Steps to reproduce the problem

1. Create a collection with a boolean field
2. In Publish create a new entry with the boolean field not set
3. Observe in the API that the field is not present.

### Package details

1.0.3-beta

**Comment by mingard** [comment]
We deliberated over this a while ago, and concluded at that point that Publish should not be saving any fields that haven’t technically been altered. Technically a Boolean field that is `undefined` or `null` is falsy. `if (document.isPublished) {...}` would be a skipped conditional statement.

**Comment by mingard** [comment]
Closing this issue as per previous comment.
