### ISSUE TITLE
Validation still enforced when required flag is falsy

### ISSUE THREAD

**Issue by mingard** [dadi/publish#365]
The following field struct includes validation, but does not explicitly force the field to be set. Validation rules running on the field are still enforced and block the save action, as well as displaying an error on the field container.

```json
"title": {
      "type": "String",
      "label": "Title",
      "required": false,
      "message": "Must be between 3 and 50 characters long",
      "validation": {
        "minLength": 3,
        "maxLength": 50
      },
      "publish": {
        "section": "Books",
        "placement": "main",
        "display": {
          "list": true,
          "edit": true
        }
      }
    },
```

**Comment by eduardoboucas** [comment]
This should wait for https://github.com/dadi/api/issues/451.

**Comment by jimlambie** [comment]
@eduardoboucas  Is this perhaps an issue for API, rather than Publish?

**Comment by eduardoboucas** [comment]
> @eduardoboucas Is this perhaps an issue for API, rather than Publish?

I believe so, yes. Also, once we have the chance to work on https://github.com/dadi/api/issues/451, both API and Publish will be able to use the same engine for validation, so whatever rules we implement will apply to both automatically.

**Comment by eduardoboucas** [comment]
This should now be fixed. If not, please reopen.
