### ISSUE TITLE
Header spacing & alignment

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#369]
Right is ✅ 

<img width="856" alt="screen shot 2018-06-06 at 14 01 55" src="https://user-images.githubusercontent.com/649231/41039722-437e713c-6992-11e8-8de0-e5f8e9e6c57e.png">

**Comment by danwdart** [comment]
hmm.. I think this is that everything is about 2/3 as spaced

**Comment by danwdart** [comment]
Do we want the hover background of the menu to have no margin - so as to end on the left of the screen?

**Comment by danwdart** [comment]
![screenshot_20180705_165642](https://user-images.githubusercontent.com/334257/42334118-67129e68-8074-11e8-844b-4be95008213d.png)
I mean like this?

**Comment by eduardoboucas** [comment]
This is ready to be tested on the preview instance. @paulrgn

**Comment by jimlambie** [comment]
@danwdart  @eduardoboucas I think the only thing we're missing on this is a `font-weight: 700` on active menu items.

**Comment by danwdart** [comment]
I think we decided that was a different ticket now
