### ISSUE TITLE
Dropdown nav size & spacing

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#371]
### Expected behavior

<img width="285" alt="screen shot 2018-06-06 at 14 05 30" src="https://user-images.githubusercontent.com/649231/41039937-df8253dc-6992-11e8-94ef-2b4bb346fafd.png">

### Actual behavior

<img width="266" alt="screen shot 2018-06-06 at 14 05 20" src="https://user-images.githubusercontent.com/649231/41039931-db70ae88-6992-11e8-8adb-22f016dca287.png">

**Comment by jimlambie** [comment]
Tasks:

 - [ ] tighten up spacing
 - [ ] highlight selected parent nav item (content & magazine in here)

**Comment by danwdart** [comment]
Almost got this, just need to leave space for the emboldening so it doesn't redraw.

**Comment by eduardoboucas** [comment]
This is ready to be tested on the preview instance. @paulrgn

**Comment by jimlambie** [comment]
@eduardoboucas @danwdart I can't see this change on http://publish-develop.eb.dev.dadi.technology/articles
