### ISSUE TITLE
Collection sort order

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#372]
Is it possible to set a default per collection? (e.g., publish date descending) Or is this done in API schema?

**Comment by mingard** [comment]
This is pulled from API schema to avoid adding any logic to Publish.

**Comment by abovedave** [comment]
Publish seems to ignore the API schema, see #133

**Comment by mingard** [comment]
Ah I see. Okay, should be a quick fix.

**Comment by danwdart** [comment]
Not sure where I'm looking on this one - could someone maybe point me in the right direction?
I gather that when collections are fetched the render needs to include the default sort options from the collection fetched, I think related to `getCollectionForUrlParams` right?
