### ISSUE TITLE
Document grid alignment when only 1 column

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#373]
<img width="232" alt="screen shot 2018-06-06 at 14 13 21" src="https://user-images.githubusercontent.com/649231/41040310-f7a234b8-6993-11e8-83ac-da066bf84cd6.png">

**Comment by danwdart** [comment]
I think this requires approval of https://github.com/dadi/publish/issues/369

**Comment by danwdart** [comment]
Just confirming whether it was definitely approved, and then will unblock this

**Comment by danwdart** [comment]
Did the other ticket fix this issue too then?

**Comment by danwdart** [comment]
Can this be closed then?

**Comment by jimlambie** [comment]
Ok, looks like it still needs some style tweaks, see this one for example

**1 column**
http://publish-feat-whitelabel.eb.dev.dadi.technology/content/images/new

**2 columns**
http://publish-feat-whitelabel.eb.dev.dadi.technology/articles/5351cd1f-31bc-435d-81d5-a17565041a6d
