### ISSUE TITLE
Reveal keyboard shortcuts

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#374]
<img width="167" alt="screen shot 2018-06-06 at 14 16 45" src="https://user-images.githubusercontent.com/649231/41040415-41e75cf6-6994-11e8-937e-739e15dd0128.png">

We had a tooltip in the prototype (perhaps have an option in the config to show these?), or we could do iOS style and have an overlay on each page:

![images duckduckgo](https://user-images.githubusercontent.com/649231/41040391-302fb454-6994-11e8-81aa-2222c200eacd.png)

**Comment by jimlambie** [comment]
@abovedave make a decision buddy! blocked until crayons.

**Comment by eduardoboucas** [comment]
@josephdenne is this something we want to pursue?
