### ISSUE TITLE
Ability to hide document section tabs when only one

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#377]
Or could be the default behaviour not to show if only one?

### Expected behavior

<img width="289" alt="screen shot 2018-06-06 at 14 29 03" src="https://user-images.githubusercontent.com/649231/41041060-fe695f5e-6995-11e8-97ea-39a4d46668dc.png">

### Actual behavior

<img width="360" alt="screen shot 2018-06-06 at 14 28 36" src="https://user-images.githubusercontent.com/649231/41041072-0337c61a-6996-11e8-9a01-ae562528bcd6.png">

**Comment by eduardoboucas** [comment]
This is ready to be tested on the preview instance. @paulrgn

**Comment by jimlambie** [comment]
Reviewed and approved.
