### ISSUE TITLE
Delete confirmation box text size and spacing

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#378]
* Button sizing
* Element spacing
* Font size
* Font weight

### Expected behavior

<img width="271" alt="screen shot 2018-06-06 at 14 31 08" src="https://user-images.githubusercontent.com/649231/41041190-5a4f1f2a-6996-11e8-9828-ab8cef5f90a5.png">

### Actual behavior

<img width="311" alt="screen shot 2018-06-06 at 14 30 48" src="https://user-images.githubusercontent.com/649231/41041195-5d47de9c-6996-11e8-82f1-8959922effec.png">

**Comment by jimlambie** [comment]
Reviewed and approved.
