### ISSUE TITLE
Document save options drop-down: remember previously selected

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#379]
<img width="259" alt="screen shot 2018-06-06 at 14 33 14" src="https://user-images.githubusercontent.com/649231/41041300-929d798a-6996-11e8-8321-6a69117bda59.png">

### Expected behavior

Per-user remember the previous state of this button - handy when bulk entering data.

### Actual behavior

Always reverts to "save and continue"

**Comment by danwdart** [comment]
Should this be stored upon the user in the database, or should it only be localStorage?

**Comment by abovedave** [comment]
I think db so it persists across device and session?

**Comment by eduardoboucas** [comment]
Worth noting that currently Publish doesn't store any metadata in API, so this is something that we need to consider and plan for carefully.

**Comment by danwdart** [comment]
I think therefore that this is a synced `PUT`/`GET` to `/${version}/${db}/users` from the... redux store, maybe?

**Comment by eduardoboucas** [comment]
And who creates that `users` collection?

**Comment by danwdart** [comment]
The users would already be there, it's the same users as one logs in using, the auth?

**Comment by eduardoboucas** [comment]
We're getting rid of that authentication method in favour of ACL, remember? ☺️

**Comment by danwdart** [comment]
Of course, was a save place decided?

**Comment by eduardoboucas** [comment]
Likely this: https://github.com/dadi/api/issues/453. Until then, this one is blocked. 🚫

**Comment by danwdart** [comment]
Okay - nice thanks

**Comment by eduardoboucas** [comment]
⏳ Waiting for API 4.2.

**Comment by eduardoboucas** [comment]
This can now be worked on, since API 4.2.0-rc4 (which the preview instance is running) includes support for arbitrary data against client records.

I propose a field for storing this preference, like `publishSaveOptionsLastUsed` (all fields should start with `publish`). [This action](https://github.com/dadi/publish/blob/develop/frontend/actions/userActions.js#L34-L89) allows you to save data against the client, so you should be able to use that.

If you have any questions, ping me on Slack.

**Comment by danwdart** [comment]
Has the location for getting client data back out changed at all?

**Comment by eduardoboucas** [comment]
Should all be [here](https://github.com/dadi/publish/blob/develop/frontend/reducers/user.js#L16).

**Comment by danwdart** [comment]
cool thanks

**Comment by danwdart** [comment]
@eduardoboucas this custom field, should it go under "data" in the user?

**Comment by danwdart** [comment]
I figured it is "data" and made it work without any extra API changes.
