### ISSUE TITLE
Checkbox/bool field adjustments

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#383]
### Expected behavior

<img width="464" alt="screen shot 2018-06-06 at 14 45 17" src="https://user-images.githubusercontent.com/649231/41041909-41463e44-6998-11e8-967c-5aae7dcecfd5.png">

- [x] adjust padding
- [x] hover state (text black)
- [x] whole box is hit area
- [x] use cursor: pointer

[edit: added checkboxes]

### Actual behavior

<img width="336" alt="screen shot 2018-06-06 at 14 44 18" src="https://user-images.githubusercontent.com/649231/41041882-33f313b6-6998-11e8-9faa-e0ab17dc2a41.png">

**Comment by danwdart** [comment]
[x] whole box is hit area

**Comment by danwdart** [comment]
> use cursor: pointer
This is true of the checkbox - does it need to be so for the whole label box?

**Comment by jimlambie** [comment]
I believe so - if the whole box is the hit area then it follows that the whole box should force a pointer? /cc @abovedave

**Comment by eduardoboucas** [comment]
> this should somehow "know" that it has a bool inside it and alter its own styles because of it, right? That doesn't seem right.

I agree, it's not the right approach. It's tricky. I came across a few situations like this in the past (can't remember which components exactly). Instead, could we make the inner component tell the parent that it needs a variation in styles?

**Comment by danwdart** [comment]
Sounded worse to me, but might make sense if I've understood properly...

So we'd pass a parent function as a prop to the child, with a param which is an object of styles, I suppose?
Then upon CDM the child could say (or handler thereof) `this.props.updateParentStyle({cursor: 'pointer'})`? That would then re-render the parent and thus the child - so I suppose `updateParentStyle` could basically do an "ensure" so if it's not there, re-render, if it's there ignore?

**Comment by eduardoboucas** [comment]
It doesn't sound great, does it? Forcing the parent to re-render isn't ideal.

What other options do we have?

**Comment by danwdart** [comment]
I'll look to see if at any point we always know higher up that we're going to be putting a bool in, and at that point add an extra style to the parent label? If we don't, we'll need a better approach, like a "AlwaysPointerLabel" or something.

**Comment by eduardoboucas** [comment]
Sounds good. 👍 🎯

**Comment by danwdart** [comment]
At the moment we always do know when we're about to pass a boolean, so I'll add an extra prop / class for it to Label and use it every time we do.

**Comment by danwdart** [comment]
Don't know if it needs a transformation or anything but the hover's there now.

**Comment by danwdart** [comment]
Seems to have been included in https://github.com/dadi/publish/pull/402

**Comment by eduardoboucas** [comment]
This is ready to be tested on the preview instance. @paulrgn

**Comment by jimlambie** [comment]
Reviewed and approved.
