### ISSUE TITLE
Media collections

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#385]
### Expected behavior

Be able to view media collection and edit/delete/add files (image to start?)

![screen shot 2018-06-06 at 14 57 49](https://user-images.githubusercontent.com/649231/41042613-0518b7e2-699a-11e8-8fe7-75f71b3a84ee.png)

### Actual behavior

You cannot see any media collections

**Comment by danwdart** [comment]
The cloud images collection did look a little like this with some CSS tweaking. I suppose one needs to enable media in the menu first though.

**Comment by danwdart** [comment]
Having a look to see if I can enable this atm (i.e. this afternoon)

**Comment by danwdart** [comment]
cc @abovedave @eduardoboucas

**Comment by danwdart** [comment]
Had a lot of trouble with this - but this is what I considered:
* Publish show menu item for media
* Publish route for media collection(s) should already exist but doesn't go anywhere - is it a bug?
* Pretend that the API gave it in the list of collections - but seems hacky

**Comment by eduardoboucas** [comment]
> Pretend that the API gave it in the list of collections - but seems hacky

Not sure if this helps, but Publish uses the `/api/collections` endpoint from API to populate the list of collections, and this endpoint makes a clear distinction of normal vs. media collections. Example:

```json
{
    "collections": [
        {
            "version": "vjoin",
            "database": "testdb",
            "name": "books",
            "slug": "books",
            "path": "/vjoin/testdb/books"
        },
        {
            "version": "vjoin",
            "database": "testdb",
            "name": "users",
            "slug": "users",
            "path": "/vjoin/testdb/users"
        },
        {
            "version": "vtest",
            "database": "testdb",
            "name": "test-schema",
            "slug": "test-schema",
            "path": "/vtest/testdb/test-schema"
        }
    ],
    "media": {
        "buckets": [
            "mediaStore"
        ],
        "defaultBucket": "mediaStore"
    }
}
```

> Publish show menu item for media

I think it's sensible for Publish to display the media collections in the nav, but not sure where/how. Does it add a new top-level menu called "Media" at the end of the list of collections?

> Publish route for media collection(s) should already exist but doesn't go anywhere - is it a bug?

Where do you see that? API has changed the way it handles media recently. We used to allow normal collections to become media collections by using a `type` property. That's no longer the case. Maybe what you're seeing is an old collection.

**Comment by danwdart** [comment]
Yep that's what I saw, so I suppose API /media is fine, Publish just gave the invalid route error despite the route being defined, when you went to /media, /mediaStore has never worked but /media/x is supposed to work too.

**Comment by danwdart** [comment]
Might be easier to add it in the list of "normal" collections in API, and mark it as media, to be dealt with in a similar way.

**Comment by danwdart** [comment]
Either way this sounds pretty big.

**Comment by danwdart** [comment]
Added the fixes in #463

**Comment by danwdart** [comment]
Now, the routes can be added to new doc list views, but investigating the existing part that looks like this, to be reused.

**Comment by eduardoboucas** [comment]
Let me know when the PR is ready to review and I'll have a look.

**Comment by danwdart** [comment]
Not having a very good time cloning stuff - please let me know what you recommend cloning - I keep coming against either route issues or nothing existing. I don't really want to clone everything especially - it would be nice to use Document stuff for some of it.

**Comment by danwdart** [comment]
Able to continue I think given appropriate splitting out of things.

**Comment by danwdart** [comment]
As per the design given, there seems to be too many ways of uploading files. I don't think we need more than this particular view - just enough to add / delete. I think the "create new" option in the toolbar shouldn't be here since there's already a "drop to upload" or "select files"

which by the way - is this meant to be the same thing as others we have now, which is "select existing file" / "drop files to upload" / "select files from device"?

I also don't think it needs "select existing file" - as duplication in this "media collection" makes no sense.

Looks like the things left are to ensure deleting / filtering works (are we using the same filter view in the document view, it's evolved hasn't it?) and uploading from this view.

**Comment by eduardoboucas** [comment]
> I think the "create new" option in the toolbar shouldn't be here since there's already a "drop to upload" or "select files"

Agree. I would remove "Add new" from the toolbar and the "Select files" button. The way to upload new files would be to drag them onto this view.

> Looks like the things left are to ensure deleting / filtering works (are we using the same filter view in the document view, it's evolved hasn't it?) and uploading from this view.

Yep.

**Comment by danwdart** [comment]
Cool thanks

**Comment by danwdart** [comment]
Please use the media views branch for extra work on this.

**Comment by eduardoboucas** [comment]
🚀
