### ISSUE TITLE
Not specifying correct database here can cause non-authenticated-properly errors

### ISSUE THREAD

**Issue by danwdart** [dadi/publish#392]
If users already a collection in another database, it's possible a cached collection handler can be returned here - not specifying the correct database here can cause non-authenticated properly errors.

https://github.com/dadi/publish/blob/5dbb4fb7a2e3e3606de7b710812faa169d93c86c/scripts/api-install/hooks/publish-auth.js#L204

The caching in the collection handler is here:
https://github.com/dadi/api/blob/develop/dadi/lib/model/index.js#L599

**Comment by jimlambie** [comment]
Life has moved on a fair way since this was raised. Reopen if this is still an issue, please.
