### ISSUE TITLE
Alignment on image upload screen

### ISSUE THREAD

**Issue by paulrgn** [dadi/publish#393]
Please review and if necessary adjust layout of image upload screen (http://publish.dadi.cloud/content/images/new). Is the placement of 'Drop files to upload or' and
'Select from device' as intended?

**Comment by paulrgn** [comment]
<img width="1432" alt="screen shot 2018-06-12 at 09 43 49" src="https://user-images.githubusercontent.com/4246879/41280190-424080c4-6e26-11e8-873a-6a5726b87601.png">

**Comment by abovedave** [comment]
Here's a new design we can try:

![artboard](https://user-images.githubusercontent.com/649231/41297456-11d75b48-6e57-11e8-8625-a417dd95ea0b.png)

Part of this is also #373

**Comment by danwdart** [comment]
Would I need to take this one back and modify the drop target stuff?

**Comment by abovedave** [comment]
I think let's make drop target a separate issue

**Comment by eduardoboucas** [comment]
This is ready to be tested on the preview instance. 🔍
