### ISSUE TITLE
Adjust default sort order for articles index

### ISSUE THREAD

**Issue by paulrgn** [dadi/publish#394]
### Expected behavior
Articles index (http://publish.dadi.cloud/articles) shows newest articles first by default

### Actual behavior
Shows oldest articles first

### Steps to reproduce the problem
Visit http://publish.dadi.cloud/articles

### Package details
n/a

**Comment by jimlambie** [comment]
Related to https://github.com/dadi/publish/issues/372

**Comment by paulrgn** [comment]
@abovedave is this a duplicate of https://github.com/dadi/publish/issues/372?

**Comment by paulrgn** [comment]
@jimlambie great minds...

**Comment by eduardoboucas** [comment]
Hey, is this a duplicate of #372?

(Sorry.)
