### ISSUE TITLE
Incompatibility with API data connectors other than MongoDB

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/publish#397]
The document edit view expects a document ID in the URL, but [the regular expression](https://github.com/dadi/publish/blob/master/app/lib/helpers/collection-routes.js#L8) used by the router to detect it uses a format that is specific to MongoDB. When API uses a different data connector, like Filestore, the format will be different.

Either we find an expression that is generic enough to handle various formats, or we make API tell consumer applications what the document ID format is.

**Comment by jimlambie** [comment]
As a simple modification, we could just make it "numbers, letters, hyphens"..... if API doesn't recognise the ID you'll get a 404 anyway, which is the same result as 404ing for an unknown format.
