### ISSUE TITLE
 Create new document not working

### ISSUE THREAD

**Issue by anaumovets** [dadi/publish#405]
When pressing _Create New_ button, empty interface is shown.
Top level collections work fine, this is only reproduced on nested collections
### Expected behavior
New document is created

### Actual behavior
Empty UI and console error:
```
Uncaught (in promise) TypeError: Cannot set property 'path' of undefined
    at DocumentRoutes.getAllCollections (document-routes.js?f1ad:117)
    at DocumentRoutes.getCurrentCollection (document-routes.js?f1ad:96)
    at Header.render (Header.jsx?4a6e:64)
    at renderComponent (preact.esm.js?acc9:728)
    at setComponentProps (preact.esm.js?acc9:676)
```

### Steps to reproduce the problem
Press _Create New_ button
### Package details
Package version, operating system, etc

**Comment by danwdart** [comment]
Any luck with this? I think this blocks a couple of tickets. I'm coming across this and I think it's related to the routes being wrong and not taking the subcategory into account.

**Comment by danwdart** [comment]
I think this is fixed now right @eduardoboucas ?

**Comment by eduardoboucas** [comment]
I believe so. @anaumovets can you confirm, please? You can test it on the preview instance.

**Comment by anaumovets** [comment]
Yes, this works!
