### ISSUE TITLE
Existing document fields overridden by saved draft

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#412]
### Expected behavior

Fields stay with their existing value.

### Actual behavior

Field is overridden by the value saved in a draft.

### Steps to reproduce the problem

1) Go to a collection
2) Hit 'Create new'
3) Type in a field
4) Go back to the collection in 1)
5) View an existing document
6) Observe the value of 3. is now in the corresponding 5. document field (although not saved at this stage)

### Package details

Chrome latest (67.0.3396.99)

**Comment by jimlambie** [comment]
@abovedave @davidmacp is this still an issue or has it been resolved in the latest beta release?

**Comment by davidmacp** [comment]
@jimlambie Just checked on http://publish-develop.eb.dev.dadi.technology/

And it is still happening there.

Is that running against the latest beta release? Not sure where to check that 🤔
