### ISSUE TITLE
Signin button grey/inactive when autofilled

### ISSUE THREAD

**Issue by mingard** [dadi/publish#420]
### Expected behavior

Sign in button should be active when fields are populated

### Actual behavior

Sign in button is grey. On desktop it changes when you click anywhere around it, but this does not resolve the problem on mobile browsers.

### Steps to reproduce the problem

Sign out, refresh page, observe autofilled credentials.

![screen shot on 2018-07-19 at 17_01_56](https://user-images.githubusercontent.com/1352469/42955390-88384276-8b75-11e8-9658-fe143c3eeca6.png)

### Package details
Latest NPM release, iOS

**Comment by jimlambie** [comment]
Retested in Chrome, works as expected
