### ISSUE TITLE
Multi-language support for documents

### ISSUE THREAD

**Issue by jimlambie** [dadi/publish#432]
* In Publish, perhaps each field is displayed like so:

![artboard](https://user-images.githubusercontent.com/649231/40910104-2c4443ee-67e3-11e8-872c-5ae0e5ec1341.jpg)

![artboard copy](https://user-images.githubusercontent.com/649231/40910110-30866a86-67e3-11e8-9ef8-b482898b1a70.jpg)

**Comment by eduardoboucas** [comment]
Me likes it.

**Comment by danwdart** [comment]
Is there a doc for the multi language support here?

**Comment by eduardoboucas** [comment]
You mean API documentation? If so, it's [here](https://docs.dadi.cloud/api/4.1#multiple-languages).

I think I'm going to take this ticket myself. I have some ideas on how to tackle it.
