### ISSUE TITLE
Ensure fields are rendered if optional schema properties are missing

### ISSUE THREAD

**Issue by lshchur** [dadi/publish#435]
Re: https://github.com/dadi/publish/blob/6ffe829feefee5a0202ae5926fa502c75fa9b92e/frontend/components/FieldString/FieldStringEdit.jsx#L127

James: we need a ticket for defaulting to the name of the field when label is missing

**Comment by danwdart** [comment]
Is this for all FieldString/FieldNumber etc?
I'd suggest that we further abstract a generic FieldText and have FieldString/FieldNumber just be validators for it maybe - different from TextBox - I'm having to do something very similar with it here and don't want to step on everybody's toes

**Comment by lshchur** [comment]
It's actual for FiledNumber, yes, because in it, it's also wrapped by Label which is given a prop `label={schema.label}`

With FieldImage, for example, it's a bit different. In there the passed label equals ```schema.label || schema._id```, so there's some kind of a fallback value in case if `label` is not specified
With FieldPassword it's also different, just for the record
```label={`Current ${schema.label.toLowerCase()}`}```

**Comment by danwdart** [comment]
Sorry my comment went on the wrong issue somehow

**Comment by danwdart** [comment]
So should `schema.label || schema._id` be passed to the rest?

**Comment by lshchur** [comment]
Yes, that sounds about right.

**Comment by eduardoboucas** [comment]
Just wanted to add that Publish should be able to render any field as long as it has a `type` property. Everything else should be optional.

If that's okay, I'm going to change the title of this ticket so the scope becomes ensuring the above is respected.
