### ISSUE TITLE
Circular reference in collection schemas causes max stack error

### ISSUE THREAD

**Issue by jimlambie** [dadi/publish#442]
When using an API collection (collection `A`) that has a Reference field which references a collection (collection `B`) that has a Reference field pointing back to collection `A`, Publish silently errors with "Max stack exceeded", and the message on the frontend is "API failure"

The error happens in the `generateApiRoutes` method when getting the maximum reference field depth.

### Use case
1. `Books` references `Authors`
2. `Authors` has property `favouriteBooks`, referencing `Books`

Ref: https://github.com/dadi/publish/blob/develop/app/lib/helpers/collection-routes.js#L51

**Comment by danwdart** [comment]
Sounds a reasonable response for the default being "fetch and include in document whenever it's referenced" - how about adding the "Actually don't grab and compose this reference" option?

**Comment by jimlambie** [comment]
@danwdart  There is actually a reasonably simple fix for this, I should have it ready later today

**Comment by eduardoboucas** [comment]
Done in #450.
