### ISSUE TITLE
Enable Sign In button without having to click outside inputs

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/publish#451]
To replicate:

1. Land on /sign-in
2. Fill in username, hit Tab
3. Fill in password
4. Observe that the Sign In button is still disabled

**Comment by davidmacp** [comment]
@eduardoboucas this might be related too:

When invalid credentials used to sign in error message is thrown - `Email not found or password incorrect`

If user attempts to correct mistake then the `Sign In` button becomes disabled again and there is no way to activate it i.e. tab or clicking between fields - a hard refresh of page is required.

http://publish-develop.eb.dev.dadi.technology/sign-in

Error triggered for invalid username

![screen shot 2018-08-23 at 11 02 46 am](https://user-images.githubusercontent.com/36462430/44498844-5d110f00-a6c4-11e8-906f-db6182b00d1e.png)

Attempt to correct username, sign in button disabled

![screen shot 2018-08-23 at 11 03 15 am](https://user-images.githubusercontent.com/36462430/44498857-7dd96480-a6c4-11e8-8f64-40874624be37.png)

**Comment by eduardoboucas** [comment]
#460 has a fix for this, but worth noting the following caveat. The implementation of the autofill feature in some browsers (e.g. Chrome) is a bit annoying in that the form elements are automatically populated but no `onChange` events are fired until the user interacts with the page. For this reason, the initial state of the Sign in button must be _enabled_, otherwise we risk showing a disabled button with a form fully filled in (i.e. when autofill kicks in). Any method for detecting autofill is hacky and bound to break in a future browser verison.

We can still disable the button when validation isn't satisfied, but only after the user has interacted with the form.

**Comment by danwdart** [comment]
Similar to save boxes and validation although I was pleased to find that that works properly now.

**Comment by danwdart** [comment]
(by which I mean that the sign in box is available again now)
