### ISSUE TITLE
Success message on profile page shows for >5 seconds

### ISSUE THREAD

**Issue by davidmacp** [dadi/publish#470]
### Expected behavior
Change password or first/last name on the `/profile` pages successfully and the `Your profile has been updated` message should display for a few moments to confirm action.
### Actual behavior
Change password or first/last name on the `/profile` pages successfully and the `Your profile has been updated` message gets displayed for approximately 10-11 seconds before disappearing. During this time user is unable to click any buttons in the top nav bar to `Sign out` for example.
### Steps to reproduce the problem
1. Sign In and navigate to http://publish-develop.eb.dev.dadi.technology/profile
2. Either change password on `Credentials` tab OR change name on `Personal details` tab
3. Click `Save settings`
4. Success message appears at top of screen
5. Click `Sign out`

![screen shot 2018-08-30 at 7 33 43 pm](https://user-images.githubusercontent.com/36462430/44843861-b234be00-ac8c-11e8-90ab-464fd9307652.png)

**Comment by jimlambie** [comment]
@davidmacp please test here 

http://publish-feature-shorter-notification-duration.eb.dev.dadi.technology/articles/48aaa1b6-61b6-46ad-b5e2-87a1baaec4d8

**Comment by davidmacp** [comment]
@jimlambie works well! 👍
