### ISSUE TITLE
DateTime is still editable when set to readonly

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#478]
### Expected behavior

The field is disabled.

### Actual behavior

You can edit the field as normal

### Steps to reproduce the problem

```json
"publishedAt": {
  "type": "DateTime",
  "format": "unix",
  "label": "Publish date/time",
  "publish": {
    "section": "Main",
    "placement": "sidebar",
    "readonly": true,
    "display": {
      "edit": true,
      "list": true
    }
  }
}
```

**Comment by jimlambie** [comment]
@davidmacp @abovedave Can be tested here: 
http://publish-patch-readonly-datetime-v2.eb.dev.dadi.technology/articles/d1452600-6ac3-4555-bb63-d35510a450d2

**Comment by davidmacp** [comment]
@jimlambie 

Re-tested on above URL. DateTime field is read only when creating OR editing an article.

Noted though and this is also happening on http://publish-develop.eb.dev.dadi.technology/sign-in

If a new article is created a Date & Time is stamped

![screen shot 2018-09-11 at 10 06 10 am](https://user-images.githubusercontent.com/36462430/45330826-a27d7980-b5aa-11e8-808a-8dd0cdd345f3.png)

However, when editing that article there is no date & time displayed

![screen shot 2018-09-11 at 10 06 30 am](https://user-images.githubusercontent.com/36462430/45330866-cccf3700-b5aa-11e8-8700-96486b4a9609.png)

**Comment by jimlambie** [comment]
@davidmacp are you sure? I see one here http://publish-patch-readonly-datetime-v2.eb.dev.dadi.technology/articles/66477d59-b5ce-4a23-9000-268d7d41516d

**Comment by jimlambie** [comment]
@davidmacp note that when testing new versions of Publish, you _may_ have to clear the application data from devtools
