### ISSUE TITLE
Default filter operators

### ISSUE THREAD

**Issue by mingard** [dadi/publish#488]
For fields with type `String` the current default filter operator is _equals_ and should perhaps be _contains_. There may be other types that need revisiting. Possibly `Boolean` fields should either be `yes` or the `default` param if set.

**Comment by danwdart** [comment]
How about

Boolean: on/off
String: contains, exactly
Number and DateTime: exactly, >, <, >=, <=, <=>
Reference: contains, exactly
Password: banned
Image: subfilter like {filename: like string, size: like number}

**Comment by mingard** [comment]
I wouldn't change the word 'equals' for 'exactly'. It doesn't read well:

Reads wrong: Where "title" exactly "foo"
Reads better: Where "title" equals "foo"

For a first pass of this issue, can we just change the default option for string from "equals" to "contains"?

**Comment by danwdart** [comment]
Yeah I just meant meaning, not name

**Comment by eduardoboucas** [comment]
This has been addressed with the new filters piece.
