### ISSUE TITLE
Unable to click `Add Filter` button

### ISSUE THREAD

**Issue by davidmacp** [dadi/publish#491]
### Expected behavior
Clicking `Add Filter` button should give user option to add a filter to search.

![screen shot 2018-09-14 at 2 42 56 pm](https://user-images.githubusercontent.com/36462430/45530472-2c894480-b82e-11e8-8209-b7786e99b740.png)

### Actual behavior
`Add Filter` button is not 'clickable' and unable to filter
(n.b. `COMMAND + F` on Mac displays the filter options)

![screen shot 2018-09-14 at 2 42 22 pm](https://user-images.githubusercontent.com/36462430/45530481-3612ac80-b82e-11e8-9d5d-9c69dec92930.png)

### Steps to reproduce the problem
1. Sign in to Publish http://publish-develop.eb.dev.dadi.technology/articles
2. Articles page listed
3. Try to click the `Add Filter` button

**Comment by jimlambie** [comment]
@davidmacp this looks to have been resolved, could you please retest and close if this is the case?

**Comment by davidmacp** [comment]
Working as expected now. Ok to close.
