### ISSUE TITLE
Not installable on Node 10

### ISSUE THREAD

**Issue by danwdart** [dadi/publish#511]
Latest Publish isn't installable on Node 10 due to the `ursa` library in deep dependencies not yet running on it. Current workaround is to use Node 8 via nvm or similar.

Somebody made a fix for ursa itself but it hasn't yet been merged:

See also: https://github.com/JoshKaufman/ursa/issues/167

Current Node supported version is 8, and should be 8 and 10 as of next Tuesday as per docs saying "Active LTS".

**Comment by danwdart** [comment]
Looks like versions 0.10 and 0.10.1 are ok with Node 10 - so our dependencies that use those can just be updated as long as they point to those versions or higher, too.

**Comment by danwdart** [comment]
It looks like it's just @dadi/ssl: https://github.com/dadi/ssl/blob/master/package.json#L22

**Comment by eduardoboucas** [comment]
@jimlambie has removed that module, so we can close this one.

**Comment by danwdart** [comment]
OK cool. I suppose the latest @dadi/ssl will have removed it instead of upgrading to the git version (seeing as not npm yet) so @dadi/publish needs to update to the newest @dadi/ssl?

**Comment by eduardoboucas** [comment]
I meant we have removed `@dadi/ssl`.

**Comment by danwdart** [comment]
ah oh right cool!
