### ISSUE TITLE
Deleting within document throws ReferenceError

### ISSUE THREAD

**Issue by davidmacp** [dadi/publish#519]
### Expected behavior
While editing a document user should be able to select the `Delete` button, confirm the request and delete the document
### Actual behavior
While editing a document if user selects the `Delete` button then confirms the request a console ReferenceError is thrown and page hangs.

![screen shot 2018-10-02 at 11 12 02 am](https://user-images.githubusercontent.com/36462430/46324308-1fde5c00-c636-11e8-8701-191e38f9129b.png)

![screen shot 2018-10-02 at 11 12 25 am](https://user-images.githubusercontent.com/36462430/46324318-2bca1e00-c636-11e8-961a-efa36d3681e1.png)

### Steps to reproduce the problem
1. Sign in to http://publish-develop.eb.dev.dadi.technology
2. Navigate to a document (e.g. any article)
3. Select the `Delete` button and confirm the request to delete

**Comment by eduardoboucas** [comment]
This should now be fixed in the URL you referenced. Please re-open if the issue still persists.

Thanks!
