### ISSUE TITLE
Navigating under an expired session results in 404 rather than redirect to login

### ISSUE THREAD

**Issue by danwdart** [dadi/publish#527]
### Expected behavior
I've tried to access something I no longer have the cookies for, so I should be expected to log in.

### Actual behavior
Every route 404s,

### Steps to reproduce the problem
Remove cookies from current session or wait for their expiry, then click a menu item and observe it 404s.

### Package details
Latest publish

**Comment by eduardoboucas** [comment]
What route are you seeing the 404 in? When I remove the cookie, routes actually work the same because the token is cached in the Redux store.

**Comment by eduardoboucas** [comment]
This should have been fixed with #535. Could you please re-open if still an issue? Thanks!

**Comment by eduardoboucas** [comment]
The issue is still there if the user's machine goes to sleep and then wakes up after the token has expired.
