### ISSUE TITLE
Rich editor: overflow scroll on code blocks

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#529]
### Expected behavior

Code blocks should scroll internally, rather than the whole editor field e.g., like github:

```
hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world 
```

### Actual behavior

The whole view is scrollable horizontally:

<img width="948" alt="screenshot 2018-10-10 at 13 12 10" src="https://user-images.githubusercontent.com/649231/46735429-2734e380-cc8e-11e8-9e68-a8d1c6b6e6dc.png">

### Steps to reproduce the problem

Insert a long line length code block

**Comment by eduardoboucas** [comment]
This looks like it has been fixed. Did you add it as part of https://github.com/dadi/publish/commit/28522c5a49dd8910ba562ee3c4a9db8b28883925?
