### ISSUE TITLE
Date & Time in document list view keeps updating

### ISSUE THREAD

**Issue by davidmacp** [dadi/publish#550]
### Expected behavior
Date & Time field for a document list view is set to when the article is created/edited

### Actual behavior
Date & Time field for a document list view gets constantly updated when refreshing the page

New Article created

![screen shot 2018-10-19 at 2 07 19 pm](https://user-images.githubusercontent.com/36462430/47195974-239a0e80-d3aa-11e8-98ad-c3e7537785e6.png)

Second article created

![screen shot 2018-10-19 at 2 10 14 pm](https://user-images.githubusercontent.com/36462430/47195982-2a288600-d3aa-11e8-9e32-c18e714f721f.png)

View articles a few minutes later

![screen shot 2018-10-19 at 2 16 43 pm](https://user-images.githubusercontent.com/36462430/47195991-31e82a80-d3aa-11e8-90fe-3c15f1b97d00.png)

### Steps to reproduce the problem
1. Navigate to http://publish-develop.eb.dev.dadi.technology/articles
2. Create articles x2
3. View in document list view and note Date & Time
4. Edit article or refresh view

**Comment by jimlambie** [comment]
@davidmacp I believe this is because you aren't providing a "publishedAt" value when creating articles. Add `publishedAt: Date.now()` to your test suite and then retry the above for me?

**Comment by jimlambie** [comment]
Fixed in API
