### ISSUE TITLE
Rich editor: Nesting <p> in <li> tags

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#561]
Seems to happen with existing saved documents

### Expected behavior

```
<li>The content</li>
```

### Actual behavior

```
<li>
   <p>The content</p>
</li>
```

**Comment by eduardoboucas** [comment]
Needs investigation.

**Comment by eduardoboucas** [comment]
This is expected behaviour as per the markdown spec (see https://github.com/markedjs/marked/issues/1298). I have changed the styling so that the nested paragraphs are shown correctly. The Markdown output is not affected.
