### ISSUE TITLE
Uncaught TypeError when creating/editing article

### ISSUE THREAD

**Issue by davidmacp** [dadi/publish#579]
The following error is displayed in console when creating OR editing an article

```
Uncaught TypeError: Cannot read property 'contains' of undefined
    at RichEditor.value (bundle.js:5)
    at RichEditor.value (bundle.js:5)
    at bundle.js:1
```
![screen shot 2018-11-09 at 1 24 03 pm](https://user-images.githubusercontent.com/36462430/48239697-034af600-e424-11e8-8f7c-2b2b9f2a2b29.png)

![screen shot 2018-11-09 at 1 25 36 pm](https://user-images.githubusercontent.com/36462430/48239704-0a720400-e424-11e8-9dd7-f679f045ec16.png)

### Steps to reproduce the problem
1. Navigate to http://publish-develop.eb.dev.dadi.technology/articles/new OR edit exisiting article
2. Click on a field
### Package details
1.0.14-beta

**Comment by jimlambie** [comment]
Looks to be resolved.
