### ISSUE TITLE
Unable to scroll article page after exiting Rich Text Editor fullscreen

### ISSUE THREAD

**Issue by davidmacp** [dadi/publish#580]
### Expected behavior
User can scroll up/down on article page when creating/editing
### Actual behavior
If user has entered the RTE fullscreen mode then returned to the article page the ability to scroll up/down is no longer available.
### Steps to reproduce the problem
1. Navigate to http://publish-develop.eb.dev.dadi.technology/articles/new OR edit exisiting article
2. Click on the RTE fullscreen toggle to go to fullscreen mode
3. Click on the RTE fullscreen toggle to go back to normal mode
### Package details
1.0.14-beta

**Comment by abovedave** [comment]
I think this might be fixed here, but we shall see next time the branch is rebuilt!

https://github.com/dadi/publish/blob/670f00f0694b6d433123116071816812534184ec/frontend/components/RichEditor/RichEditor.jsx#L439-L444

**Comment by eduardoboucas** [comment]
It works for me. Please re-open if the issue persists.
