### ISSUE TITLE
Mobile nav not scrollable

### ISSUE THREAD

**Issue by mingard** [dadi/publish#582]
### Expected behavior
Ability to scroll entire collection navifgation

### Actual behavior
Some properties below the fold are unreachable

### Steps to reproduce the problem
- Open on mobile chrome
- Attempt to scroll where the height of collection `<li>` elements exceeds the available viewport height.

### Package details
1.0.14-beta

Note: I believe this was previously fixed. Searched for an active ticket and could not find one. Perhaps this was the previous fix https://github.com/dadi/publish/issues/388

**Comment by jimlambie** [comment]
Closed by https://github.com/dadi/publish/commit/75c139ac9a2f70bd9d7917d523204866ff9591fd
