### ISSUE TITLE
Single document collections

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#584]
If you're building out a relatively 'static' site, it would be handy to specify that a collection only has a single document, so in Publish it skips the `list` and goes directly to the `edit` view.

A good example would be pages that have static elements made up of different fields that don't change that often e.g., homepage consisting of `headline`, `introduction` etc

**Comment by jimlambie** [comment]
There is already a publish block, which allows `hidden: true`. So a perfect place for it

**Comment by eduardoboucas** [comment]
Oh, great!
