### ISSUE TITLE
<textarea> height in fullscreen 

### ISSUE THREAD

**Issue by davidmacp** [dadi/publish#589]
When switching between normal and fullscreen while in `text` mode - should the `<textarea>` resize to display all data?

Currently when switching, the `<textarea>` seems to carry over the height from the normal view. Therefore only first few lines are shown and user has to click into `<textarea>` and scroll to see all data previously entered.

![screen shot 2018-11-12 at 4 02 08 pm](https://user-images.githubusercontent.com/36462430/48327800-d2252c80-e694-11e8-8fa7-b416427ffa3a.png)

![screen shot 2018-11-12 at 4 02 41 pm](https://user-images.githubusercontent.com/36462430/48327808-d8b3a400-e694-11e8-95cc-8b544ca9a311.png)

### Steps to reproduce
1. Navigate to http://publish-develop.eb.dev.dadi.technology/articles/new OR edit exisiting article
2. Enter data into rich editor (more than 3 lines)
3. Click on the `text` button
4. Click on the fullscreen button
### Package details
1.0.14-beta

**Comment by eduardoboucas** [comment]
@abovedave may I ask for your assistance on this one, please? 😇
