### ISSUE TITLE
Rich Editor: adding/editing links with multiple editors

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#606]
### Expected behavior

The link modal appear in the currently focused rich editor when there are more than one in the view.

### Actual behavior

The link modal of other rich editors on the page open (multiple clicks cause different fields to react).

<img width="908" alt="screenshot 2018-11-21 at 21 13 36" src="https://user-images.githubusercontent.com/649231/48863541-63517d00-edd2-11e8-90c0-2d53ad9234bf.png">

### Steps to reproduce the problem

Create a collection with multiple rich fields e.g., [dadi.cloud web services](https://github.com/dadi/cloud/blob/develop/api/workspace/collections/1.0/cloud/collection.web-services.json)

**Comment by jimlambie** [comment]
@eduardoboucas tested and approved
