### ISSUE TITLE
Media Library: Unable to delete Emma Watson

### ISSUE THREAD

**Issue by davidmacp** [dadi/publish#610]
### Expected behavior
On Media Library page user should be able to select 1 or more images/gif etc, select `Delete` from the dropdown menu, press `Apply` to trigger confirmation, then press `Yes, delete it`/`Yes, delete them` to confirm
### Actual behavior
`Yes, delete it`/`Yes, delete them` button is active but pressing on it does nothing. Emma still remains  (as does any other image/gif etc)
![screen shot 2018-11-23 at 1 50 48 pm](https://user-images.githubusercontent.com/36462430/48927026-e1269d00-ef26-11e8-8de4-574005992db7.png)

### Steps to reproduce the problem
1. Navigate to http://publish-develop.eb.dev.dadi.technology/media
2. Select an image(s) to delete
3. Select `Delete` from dropdown
4. Click on `Apply`
5. Click on `Yes, delete it`/`Yes, delete them`
### Package details
1.0.14-beta

**Comment by eduardoboucas** [comment]
Should now be fixed in `develop`. Please re-open if still an issue.
