### ISSUE TITLE
Rich Editor: issues with Return key on code blocks

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/publish#620]
### Expected behavior

When the user presses Return inside a code block, a new line is inserted within the code block.

### Actual behavior

When the user presses Return inside a code block, a new block is created.

### Steps to reproduce the problem

Create a code block, type some text and press Return. Observe a new code block being created.

### Package details

1.0.16-beta

**Comment by eduardoboucas** [comment]
@davidmacp Can you test this on `develop` and reopen if still an issue?

**Comment by davidmacp** [comment]
@eduardoboucas still having issues with this in `develop`

If I toggle the Code button ON then type in text
![screen shot 2018-11-27 at 8 58 25 am](https://user-images.githubusercontent.com/36462430/49045006-a7ee7580-f223-11e8-9573-00551da6e733.png)

When I toggle the Code button OFF to complete then the following error is seen and the text disappears
![screen shot 2018-11-27 at 8 58 49 am](https://user-images.githubusercontent.com/36462430/49045047-d10f0600-f223-11e8-9136-14c942976111.png)

However, switching to markdown view I can see the 'code text' there
![screen shot 2018-11-27 at 8 59 10 am](https://user-images.githubusercontent.com/36462430/49045077-eb48e400-f223-11e8-8247-50a7be82b453.png)

**Comment by eduardoboucas** [comment]
Confirmed. Will sort.
