### ISSUE TITLE
npm run api-install

### ISSUE THREAD

**Issue by viliamsevela** [dadi/publish#625]
### Expected behavior
Create user collection and allow to add new user as described here:
https://docs.dadi.cloud/publish/1.0.4#first-use (step 2)

### Steps to reproduce the problem
I tried to run command:
`NODE_ENV=development npm explore @dadi/publish -- npm run api-install --configDir=/Users/viliamsevela/Sites/dadi/publish/config`

There is the result:
@dadi/publish@1.0.15-beta api-install /Users/viliamsevela/Sites/dadi/publish/node_modules/@dadi/publish
node scripts/api-install/api-install.js

ERROR 404 - undefined
Creating User Collection
(node:51902) UnhandledPromiseRejectionWarning: TypeError: (intermediate value).in(...).setConfig is not a function
    at APIInstall.createUserCollection (/Users/viliamsevela/Sites/dadi/publish/node_modules/@dadi/publish/scripts/api-install/api-install.js:124:6)
    at getCollection.then.catch.err (/Users/viliamsevela/Sites/dadi/publish/node_modules/@dadi/publish/scripts/api-install/api-install.js:92:19)
(node:51902) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:51902) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Package details
Tried on those publish versions:
@dadi/publish: "^1.0.15-beta"
@dadi/publish: "^1.0.16-beta"
(same result)

**Comment by abovedave** [comment]
Sorry @viliamsevela, our docs are a bit out of date at the moment, you can read a current [first install guide here](https://dadi.cloud/en/tutorials/web-services/publish-step-by-step-first-install/)

Essentially you need to create a collection called `clientId` in your DADI API, then add a document with the credentials in. For example:

```json
{
    "clientId": "yourclientid",
    "secret:": "somethinglongandsecure",
    "accessType": "admin"
}
```

You then log into Publish interface with those creds.

Any questions, let me know.

**Comment by viliamsevela** [comment]
Thank's, no problem. Now it's working 👍

**Comment by abovedave** [comment]
Great, glad it's working. Just adding to the above, best practice is to use the ACL endpoints outlined in the API docs going forward:

https://docs.dadi.cloud/api/4.4#creating-a-client

Enjoy!
