### ISSUE TITLE
Media library: upload progress/feedback

### ISSUE THREAD

**Issue by abovedave** [dadi/publish#641]
Hard to know if what's being uploaded is getting through - particularly with batch uploads.
Perhaps show the thumbnail with a loading wheel?

<img width="310" alt="screenshot 2018-12-05 at 16 37 01" src="https://user-images.githubusercontent.com/649231/49528592-1e3a4a00-f8ac-11e8-87cb-c1e9eb1758c6.png">

**Comment by eduardoboucas** [comment]
This should be fixed in #717. Please reopen if still an issue.
