### ISSUE TITLE
Sorting in reference select view

### ISSUE THREAD

**Issue by jimlambie** [dadi/publish#642]
### Expected behavior

When selecting a document for a reference field, clicking on column headings to sort should sort the documents available for selection

### Actual behavior

When selecting a document for a reference field, clicking on column headings to sort goes back to the parent collection and applies the sort to that

### To reproduce

Use a collection with a reference field
Create a new document
Click "Select new whatever"
Click a column heading to sort

**Comment by eduardoboucas** [comment]
@ohmoses can you investigate if this is still an issue please?
