### ISSUE TITLE
Spec: document edit view

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/publish#67]
# What I've done so far

## Store

The document store contains:

- `data`: An object representing the document being edited
- `validationErrors`: A list of validation errors for each field (to be expanded below)

## View

`DocumentEdit` (view) reads data from state, groups fields by section and UI position. In the future, it could make sense to move some of this logic away from the view and into a container (I suspect this will make sense once we work on the media collection). The view also decides which component will render the field based on its type (for example, a field of type `String` will be handed over to the `FieldString` component)

## Field handler component and dumb UI components

`FieldString`, like every other field handler component, receives two props: 
  - `schema`: an object containing the field definition from the collection schema
  - `value`: the current value of the field in the document being edited (if any)

It then decides which (dumb) components it needs to render its contents. For example, `FieldString` currently uses `Label` and `TextInput`, but a `FieldObject` might use another set of components. Note that these dumb components have no idea what a document, collection or validation routine are. These concepts are controlled by the field components.

#### Validation

  Field components also handle validation. They read the rules from the `schema` prop they receive and can do actions on different events of their child components. For example, `FieldString` listens on `onKeyUp` to validate on every keystroke. Other components might want to listen to different events.

Field components receive two callbacks as props:

- `onError`: This will be called whenever the validation has failed for the field. It's used by the parent (view) to fire an action to the store registering the validation error, which will update the UI accordingly.

- `onErrorClear`: This will be called whenever a validation error has been cleared. Similarly, an action will be fired to the store clearing the errors for the field, updating the UI accordingly.

# What I propose going forward

## Store

The document store could have:

- `remote` (renamed from `data`): The state of the document as it currently exists on the remote API
- `local`: The state of the document as it's being edited
- `validationErrors`: Same as before.

## The flow

In addition to `onError` and `onErrorClear`, field components also receive a `onUpdate` callback. This callback will be used by the parent (view) to fire actions that will update `document.local` with the new value. Each field component can then decide when to fire this callback — for example, for `FieldString` it might make sense to only fire an update call on `onChange` and not on `onKeyUp`, but an image field might use a completely different event.

When we move to collaborative editing, the view can listen for socket events and fire update actions from other users too. The fact that the local document is always updated by actions makes it really flexible.

At any point in time, we can do a diff between `local` and `remote` to show what we're about to edit. When it's time to submit (which will only be possible if there's nothing in `validationErrors`, we push `local` to API bridge.

---

Thoughts?

**Comment by eduardoboucas** [comment]
By the way, a consequence of representing the document being edited as an object in the store means that we can, for example, store it against the user, which would allow you to work on a document on your laptop and then carry on the editing process on your mobile.

**Comment by mingard** [comment]
@eduardoboucas are you suggesting that we store any unpublished changes on the user record?

**Comment by eduardoboucas** [comment]
@mingard Not a requirement for now, I suppose. I was just highlighting the benefits of having your unpublished changes as an object that you can move around to load your state anywhere you need. I suppose the technical implementation on how you'd sync multiple devices is outside the scope of this discussion, I was just saying that it would be possible and apparently not difficult at all.

**Comment by mingard** [comment]
The alternative to this is to introduce _softHistory_ in API on a per-collection basis, and only persisted until the document has been versioned with each change.

This would differ from standard history in that it would exist to facilitate incremental temporary saving for documents during draft/edit stage. 

Advantage: 
- Would be validation against collection schema in API. Should the schema change, api could transform the results before handing to Publish.
- Would avoid interfering with the history state of a user record

**Comment by eduardoboucas** [comment]
Not sure I understand. That's an alternative to what exactly? We still need Publish to hold the state of the document being edited.

Can you detail what you'd change from the spec above?

**Comment by mingard** [comment]
Re `remote` and `local`. Like this very much. Do we expect to perform regular sync on remote. This could be as basic as `HEAD` request to the remote document API address to acknowledge `Last-Modified` and display a _document has changed_ message

**Comment by mingard** [comment]
> Can you detail what you'd change from the spec above?
Rather than holding document changes in the user record to allow device-switch, we store them in a new type of history collection. It has no baring on the document stored in state

**Comment by eduardoboucas** [comment]
> Do we expect to perform regular sync on remote.

The way I see it, when you start editing a document you take a snapshot of `remote` to build `local`. From that point on, you don't really touch `remote`.

We could indeed fetch changes from `remote` on a regular basis and try to conciliate them with `local` (only in fields that haven't yet been edited?), but I see some complexity being added here. Could we go for a simpler solution for MVP where we don't try to update `remote` and then spec something more comprehensive for post MVP?

> Rather than holding document changes in the user record to allow device-switch, we store them in a new type of history collection. It has no baring on the document stored in state

Ah, understood! Makes sense.

**Comment by eduardoboucas** [comment]
(I just re-read your comment and I think that just showing a *document has changed* message is perfectly reasonable and doable)

**Comment by mingard** [comment]
Perfect! I see that as more than enough for MVP. @josephdenne thoughts on the above?

**Comment by eduardoboucas** [comment]
Done in #72.
