### ISSUE TITLE
Rich editor inline image selection returns 404

### ISSUE THREAD

**Issue by davidmacp** [dadi/publish#683]
### Expected behavior
User creating a new document can use the rich text editor and insert an inline media image before initial save of document
### Actual behavior
User attempts to insert inline media on new/unsaved document and `404` is returned

![Screen Shot 2019-04-15 at 2 39 30 pm](https://user-images.githubusercontent.com/36462430/56104740-2ce8ea00-5f8d-11e9-931f-4319c11435e4.png)

![Screen Shot 2019-04-15 at 2 39 09 pm](https://user-images.githubusercontent.com/36462430/56104742-31150780-5f8d-11e9-825a-9fead1676bad.png)

### Steps to reproduce the problem
1. Create new article http://publish-develop.eb.dev.dadi.technology/articles/new/ and use rich text editor button to insert inline media

**Comment by eduardoboucas** [comment]
This should be fixed in #717. Please reopen if still an issue.
