### ISSUE TITLE
Reference fields container overflow

### ISSUE THREAD

**Issue by mingard** [dadi/publish#685]
Reference fields with long string with no spaces as primary text field overflow container on narrow viewport

![Screen Shot 2019-04-15 at 13 47 54](https://user-images.githubusercontent.com/1352469/56133873-5271f580-5f85-11e9-8c38-2609cc144309.png)

### Package details
2.0.0

**Comment by eduardoboucas** [comment]
@ohmoses assigning you, since you're officially our container overflow expert after solving #646. 😇
