### ISSUE TITLE
Return key on bulk actions

### ISSUE THREAD

**Issue by josephdenne** [dadi/publish#689]
### Expected behavior

When confirming a bulk action, hitting return on my keyboard should confirm the action.

### Actual behavior

Hitting return takes you back one step.

### Steps to reproduce the problem

Select one or more items in a collection index, select delete, then apply and hit your return key.

<img width="1551" alt="Screenshot 2019-04-17 at 06 47 51" src="https://user-images.githubusercontent.com/150408/56264045-26698800-60dd-11e9-9f3c-0c2dd006bdcc.png">

**Comment by josephdenne** [comment]
Note that this applies to all confirmation actions within the system, e.g. delete on an individual document.

<img width="1551" alt="Screenshot 2019-04-17 at 07 22 46" src="https://user-images.githubusercontent.com/150408/56265557-c9240580-60e1-11e9-88c3-e288c538b09a.png">

**Comment by eduardoboucas** [comment]
Added in https://github.com/dadi/publish/commit/c970d748226ed9b0287805df06a065ece105d152. @davidmacp could you kindly add some tests?
