### ISSUE TITLE
Save as duplicate reset after save

### ISSUE THREAD

**Issue by mingard** [dadi/publish#691]
When you open a document and save a duplicate, then go to save the new document, it's easy to miss the fact the button has remained "save duplicate".

Equally, this can happen if you create a duplicate and navigate to another collection's document, then hit save.

I propose the duplicate save resets after first successful use.

**Comment by eduardoboucas** [comment]
This is by design: https://github.com/dadi/publish/issues/379.

**Comment by mingard** [comment]
I think it's worth revisiting it. At least when navigating to another collection or out of the document view back to the list view. It's incredibly annoying!

**Comment by eduardoboucas** [comment]
I personally agree. Plus, we're currently saving the last used save option against the client record each time we save, which means added complexity and an extra API request.

I think _Save and continue_ should always be the main option.

**Comment by eduardoboucas** [comment]
Done in #717.
