### ISSUE TITLE
Link component

### ISSUE THREAD

**Issue by mingard** [dadi/publish#70]
Using the [router](https://github.com/dadi/publish/blob/master/docs/lib/router.md) lib, the `Link` component will take the same parameters to generate an anchor.

```html
<!-- Current path -->
<Link
  params={bar: 'baz'}
/>

<!-- new path -->
<Link
  path='/foo'
  params={bar: 'baz'}
/>

<!-- new path with existing params -->
<Link
  path='/foo'
  params={bar: 'baz'}
  update
/>
```

**Comment by mingard** [comment]
@eduardoboucas thoughts?

**Comment by eduardoboucas** [comment]
I'm a big fan of #69 and, to be honest, I don't see this component making the task of linking to a route much easier than it is to attach `createRoute()` to `<a>` directly. I do see a few potential problems with it.

Links are rarely `<a>` tags with just a `href` attribute. They will have classes for styling, the odd `style` attribute with inline styles that need to be set with data from JavaScript, as well as other attributes like ARIA for accessibility purposes. Building the `<a>` yourself allows you to specify these easily and intuitively. It's true that `<Link>` could look out for these props and pass them on to the anchor, but it's added complexity and potential points of failure.

It's also another component that we're adding to the catalog, committing to document and maintain, and it's extra cargo on the payload. I personally think #69 gives us everything we need on this front.

**Comment by mingard** [comment]
The concept was in-part based on the react-router Link element which replaces anchor.

That's a good assessment so I'll close the issue.
