### ISSUE TITLE
Addition of a digit group separator in pagination menus

### ISSUE THREAD

**Issue by josephdenne** [dadi/publish#702]
The addition of a digit group separator in pagination menus to aid visual navigation.

Current:
![current](https://user-images.githubusercontent.com/150408/56432531-a8b4a080-62c5-11e9-869f-d8a7b376bee0.png)

Intended:
![intended](https://user-images.githubusercontent.com/150408/56432537-ac482780-62c5-11e9-86f1-a6e8605ff373.png)

This should be configurable for international support. See: http://www.statisticalconsultants.co.nz/blog/how-the-world-separates-its-digits.html

**Comment by jimlambie** [comment]
Odd that you'd look to a colonial outpost for guidance, but yes this should be simple enough to do using the current locale settings. I don't think we need to make it configurable as such.

**Comment by eduardoboucas** [comment]
Added in https://github.com/dadi/publish/commit/a0e61c773a30241fc1fdd4d58f93c006eecb995d.

<img width="1959" alt="Screenshot 2019-06-12 at 16 38 21" src="https://user-images.githubusercontent.com/4162329/59365609-bc620d80-8d30-11e9-82aa-b2c35eeafef8.png">
