### ISSUE TITLE
The ability manage Publish users within Publish itself

### ISSUE THREAD

**Issue by josephdenne** [dadi/publish#705]
As an admin I would like to be able to add, remove and manage users and their permissions from within Publish itself.

This should be optional and the menu grouping and title configurable.

**Comment by eduardoboucas** [comment]
Needs some UI input. I feel that a link for this interface should sit somewhere other than the main collection navigation, to differentiate between data management and user management.

**Comment by eduardoboucas** [comment]
Closing this, as it will be part of a separate application.
