### ISSUE TITLE
Handle API errors on document save

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/publish#708]
### Expected behavior

When a user saves a document and there is an API error (e.g. 500) preventing the operation from completing, the interface should show a message informing the user that something out of their control went wrong.

### Actual behavior

Publish interprets any error as a 404 and shows the "document not found" message.

### Steps to reproduce the problem

Add a failing `beforeCreate` or `beforeUpdate` hook to a collection and attempt to save a document.

**Comment by ohmoses** [comment]
This seems to be fixed in 3.0.0. I get `An error has occurred. The document could not be created/updated`. Closing for now
