### ISSUE TITLE
Offline API causes white screen when a session is present

### ISSUE THREAD

**Issue by mingard** [dadi/publish#713]
If API is down and Publish is loaded you see the normal login screen and sign in fails with error `The API is not responding` however, if a session already exists and API is unresponsive, nothing appears.

I believe this should be a warning message which should also be used instead of the login page.

**Comment by eduardoboucas** [comment]
Can you confirm the version of Publish you're using?

**Comment by mingard** [comment]
Sure, it's 2.3.1
