### ISSUE TITLE
Clear Reference field on list view

### ISSUE THREAD

**Issue by mingard** [dadi/publish#739]
Currently a Reference field in the document view has both _Edit_ and _Remove_ but after clicking _Edit_ and entering the list view, there are only two options: _Save_, or _Cancel_. If a user unchecks all documents in the list view, the Save button is disabled, which means the user must first Cancel in order to return the document overview, and then click _Remove_. 

I propose that the Save button is only ever disabled if there is no change. If the user removes all documents they should still be able to Save, which would have the same effect as _Remove_.

**Comment by eduardoboucas** [comment]
I actually think that the Save button should never be disabled on the reference select view. Even if the value hasn't changed, there's no harm in keeping the button enabled so that people can get out of there, even if the value will remain unchanged.
