### ISSUE TITLE
Date picker obscured by autofill

### ISSUE THREAD

**Issue by mingard** [dadi/publish#743]
The date picker field allows autofill on date input which obscures the date field. 

![Screen Shot 2019-07-06 at 16 04 20](https://user-images.githubusercontent.com/1352469/60757845-daf1b680-a007-11e9-801c-8dda236ec349.png)

**Comment by eduardoboucas** [comment]
I don't think there's much we can do about the autofill, but we'll double check.

@ohmoses could you take a look, please?

**Comment by eduardoboucas** [comment]
In fact, this is essentially the same as #710. Moving the discussion there.
