### ISSUE TITLE
Filtering articles doesn't bring back all results

### ISSUE THREAD

**Issue by jobiddulph** [dadi/publish#747]
In http://develop.publish.dadi.technology/articles if I click on Add Filter and select Published is 'No' I would expect it to return all articles that are not published - 5 in total

The filter brings back 3 articles

Steps to reproduce - as above go to In http://develop.publish.dadi.technology/article, click Add Filter, select 'Published' and 'No'. You can see 5 unpublished articles if you click through the pages, but only are returned in the filter

Publish v.3.0.0

**Comment by eduardoboucas** [comment]
@jobiddulph I believe this was caused by an outdated version of API running on the preview instance. Could you please retest?

**Comment by jobiddulph** [comment]
@eduardoboucas this is now working
