### ISSUE TITLE
Rich Editor - escape characters getting displayed on front end

### ISSUE THREAD

**Issue by davidmacp** [dadi/publish#754]
### Expected behaviour
Text written in the Rich Text Editor should not display any escape characters on the front end

### Actual behaviour
Text written in the Rich Text Editor that requires escape characters results in those escape characters being displayed on the front end

Article in RTE mode with parenthesis:
![Screen Shot 2019-07-17 at 8 30 10 am](https://user-images.githubusercontent.com/36462430/61327647-87843180-a86d-11e9-8679-89cbc14975bf.png)

When viewed in `raw mode` parenthesis and dash are escaped:
![Screen Shot 2019-07-17 at 8 30 21 am](https://user-images.githubusercontent.com/36462430/61327693-a256a600-a86d-11e9-82ff-fd959a8749da.png)

When viewed on front end the escape characters are shown:
![Screen Shot 2019-07-17 at 8 35 16 am](https://user-images.githubusercontent.com/36462430/61327799-d7fb8f00-a86d-11e9-9371-fe6b93bab2d3.png)

### Package details
v3.0.0-rc3

**Comment by eduardoboucas** [comment]
This is odd, because parenthesis do not need to be escaped. We'll have a look, thanks!

**Comment by ohmoses** [comment]
This is a bug in the frontend, unfortunately.

The escaping is correct behavior: in _this particular case_ the escapes are unnecessary, but it would probably be very complicated to write a Markdown serializer where you _provably_ remove _only_ the unnecessary escapes.

If I use a correct Markdown parser (in this case Remark), it works fine: 

```markdown
[]()

\[\]\(\)

()

\(\)

-

\-
```
⇒
```html
<p><a href=""></a></p>
<p>[]()</p>
<p>()</p>
<p>()</p>
<ul>
  <li></li>
</ul>
<p>-</p>
```
This is a change that needs to be done in the frontend.

I'm closing the issue.

**Comment by davidmacp** [comment]
Thanks for looking into it @ohmoses. I will advise the dev it is a frontend issue.
