### ISSUE TITLE
FieldString: Option list

### ISSUE THREAD

**Issue by mingard** [dadi/publish#83]
A transitioning feature from v1 publish is the ability to specify options for a String, encapsulated in two parts of the field block:

```json
{
  "foo": {
    "type": "String",
    "validation": {
      "pattern": "[bar|baz]"
    },
    "publish": {
      "options": [
        {"label": "Bar", "value": "bar"},
        {"label": "Baz", "value": "baz"}
      ]
    }
  }
} 
```

@eduardoboucas outstanding question as discussed on Slack: Do we call this options? If not, what?

**Comment by eduardoboucas** [comment]
Like! As for the name, maybe `dropdownOptions`  or something like that? Just anything that makes it more obvious that the property will make the field be rendered as a dropdown in Publish, rather than some mandatory configuration options. 

What do you think?

**Comment by eduardoboucas** [comment]
Done in #84.
