### ISSUE TITLE
Toaster UI

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/publish#86]
From Slack:

>I’m looking at the toaster/info banner (http://cloud.dadi.technology/kpk3). couple of questions:
>
>1. in your mock up, it pushes down the content of the page. is this intended?
>2. it’s positioned with the header, which is not fixed positioned. this means that if I have scrolled down the page and hit save, I won’t be able to see the toaster unless I scroll all the way up again. what are your thoughts?
>3. does it automatically close itself after a period of time, or do you have to close it? the label saying “10 minutes ago” makes me thing the latter, but I don’t see any controls.

**Comment by abovebored** [comment]
Besides this save state, can you think where else this would be used? I'm wondering if we trade it in for a 'saved' button state (the saved time is already shown at the bottom of a document)

**Comment by eduardoboucas** [comment]
We'd need to display error messages in case a save operation fails, for example. We could theoretically still use the save button for that, but in some situations it might be useful to add some detail into what actually happened (is the API down? has something failed on the app side? etc.)

I can't think of any specific examples, but I think it would be a bit limiting to not have the ability to send messages to users. I was thinking of something along [these lines](http://tamerayd.in/ngToast/#). Do you think this could work?

**Comment by mingard** [comment]
Examples of possible errors

- Failed image upload
- Failed document save (connection)
- Failed document save (API)
- Failed document load (API)
- Failed save (user credentials)
- Failed authentication check

I don't see this as specific to the document edit view and it doesn't relate to format or requirement validation, which are already taken care of.

This is a globally applicable failure system.

**Comment by eduardoboucas** [comment]
@abovebored have you thought any more about this? Would be great to start building it.

**Comment by abovebored** [comment]
Like how they stack in that example @eduardoboucas, I'm worried they might get lost up there, but let's try it.

<img width="674" alt="screen shot 2017-03-23 at 11 37 12" src="https://cloud.githubusercontent.com/assets/649231/24246032/4f84d938-0fbd-11e7-89df-957c0d7d6d6a.png">

Borders are standard yellow, green & red. Backgrounds are Yellow #FFF3CD, Green #E9F8D7 & Red #E9F8D7.

**Comment by mingard** [comment]
Looking at the example usage further I'm not convinced we necessarily need a toaster. The _Saved successfully_ message is nice, so long as it disappears after a time, or on click.

For connection issues, it would be ideal if we could preemptively alert the user of a disconnection issue rather than on save. Inbox does this well.

<img width="371" alt="screen shot on 2017-03-23 at 11 3a50 3a10" src="https://cloud.githubusercontent.com/assets/1352469/24246452/534e4c14-0fbf-11e7-9a36-26fda6c69529.png">

For errors such as _Server timeout_ or anything unlikely to be resolved by repeating the same action we probably need a dialogue. Something with _Cancel_, _Retry_, _Report an issue_.

**Comment by eduardoboucas** [comment]
If we go with the "Saved successfully" message as per the design, we still need to answer the questions I raised in the first comment about whether or not it will push the content down.

**Comment by mingard** [comment]
In the version of _Saved successfully_ @abovebored shared in his last comment the overlay in centred. That resolves the issue of pushing content down.

**Comment by eduardoboucas** [comment]
Ah, sorry, I misread. I thought we were talking about the initial idea.

**Comment by eduardoboucas** [comment]
Just a quick question on the "Saved successfully" dialog: don't we want to give it a green treatment if indicating success and a red one if indicating failure?

**Comment by eduardoboucas** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/649231/24246065/7e7845e0-0fbd-11e7-8b21-094a73c85ac1.png)

^ I really like this one as a general method for displaying status messages. My idea is:

1. This is similar to the toaster proposed initially, but because it's anchored to the bottom toolbar the question about pushing content up or down isn't an issue. It just covers whatever content is below.

1. I'd use this to display success, warnings and errors, variating the background colour accordingly.

1. I'd probably add a "Dismiss" button, and potentially the option to contain other simple call to actions — thinking, for example, a message like "The document you're editing was changed recently" with a "Reload" link next to it.

It'd be great to achieve a solution for this soon, as it'd allow us to finish the create/update document piece, as well as add some nice touches to #128.

Any thoughts?

**Comment by mingard** [comment]
@eduardoboucas Agree with all the above. How can we proceed?

**Comment by eduardoboucas** [comment]
I can start building it.

**Comment by mingard** [comment]
Awesome. Please do 👍
