### ISSUE TITLE
Support for assets

### ISSUE THREAD

**Issue by mingard** [dadi/publish#93]
## Concept overview
- [ ] Assets will be stored within asset collection(s) specified within config
- [ ] Asset collections can contain one or more asset field (image/video/audio/file), nothing else.
- [ ] **AssetMeta** collections are where assets are manipulated for single-use, per-parent-collection. This is typically fields such as title, alt text, caption etc. It is also where image crops will exist. One instance of an **AssetMeta** collection might have different available crops to others.
- [ ] **AssetMeta** collections are _not_ a collection type, but will simply be shown and hidden based on business requirements.

@abovebored @eduardoboucas There is **no requirement** for the media view, outside of document edit. That means no unassigned batch uploads.

This view remains
http://cloud.dadi.technology/XtcB

**Comment by mingard** [comment]
@josephdenne make sense?

**Comment by josephdenne** [comment]
Yes.

**Comment by mingard** [comment]
Update: Media collection is no longer specified in config. It is a fixed endpoint as part of the media features in API 2.0
