### ISSUE TITLE
Batch document actions

### ISSUE THREAD

**Issue by mingard** [dadi/publish#98]
I believe we already have multi select, so all this needs is 
- [ ] action selection
- [ ] CTA
- [ ] Events
- [ ] Callback confirmation

**Comment by eduardoboucas** [comment]
I got this to the point of grabbing the IDs of the documents selected. It now needs to actually trigger an API call. Do we have designs for a "Are you sure you want to delete all this stuff" thing?

**Comment by mingard** [comment]
I don't believe so. Lets capture with a standard dialog. @abovebored do you have anything to use here?

**Comment by eduardoboucas** [comment]
@abovebored Could you share your thoughts on this when you have a sec?

**Comment by abovebored** [comment]
Could we use this from the doc editor?
<img width="280" alt="screen shot 2017-04-10 at 13 12 04" src="https://cloud.githubusercontent.com/assets/649231/24861102/5e1e70d6-1def-11e7-82d0-e36b06f27eb7.png">

**Comment by mingard** [comment]
Looks good

**Comment by eduardoboucas** [comment]
Perfect, thanks dude!
